/**
 * The Royal Bihar Restaurant Onboarding & Menu Seeding Script.
 *
 * Seeds:
 * 1. The restaurant profile for The Royal Bihar Restaurant
 * 2. The vendor account login (royalbiharrestaurant@gmail.com / royalbihartraefood123)
 * 3. All 15 categories and 120+ menu items transcribed from official menu photos.
 *
 * Usage:
 *   node --env-file-if-exists=.env.local --conditions=react-server --import tsx scripts/seed-royal-bihar.ts
 */

import { ROLE } from "@/lib/constants";
import { rupeesToPaise, type Paise } from "@/lib/money";
import { hashPassword } from "@/server/auth/passwords";
import { getMongoClient } from "@/server/db/client";
import * as db from "@/server/db/collections";
import type { AddOnGroup, MenuCategory, MenuItem, Restaurant } from "@/types/restaurant";
import type { User } from "@/types/user";
import { CAMPUS_ID } from "./seed-data";

const RESTAURANT_ID = "rest_royal_bihar_nitp";
const VENDOR_USER_ID = "usr_royal_bihar_vendor";
const VENDOR_EMAIL = "royalbiharrestaurant@gmail.com";

const R = rupeesToPaise;

function portionGroup(halfPaise: Paise, fullPaise: Paise, label1 = "Half", label2 = "Full"): AddOnGroup {
  return {
    id: "grp_portion",
    name: "Portion / Quantity",
    minSelect: 1,
    maxSelect: 1,
    options: [
      { id: "opt_portion_half", name: label1, pricePaise: 0, isAvailable: true },
      { id: "opt_portion_full", name: label2, pricePaise: fullPaise - halfPaise, isAvailable: true },
    ],
  };
}

/* ══════════════════════════════════════════════════════════════════════
   Categories
   ══════════════════════════════════════════════════════════════════════ */

const CATEGORIES: { id: string; name: string; sortOrder: number }[] = [
  { id: "cat_rb_veg_starters", name: "Veg Starters", sortOrder: 1 },
  { id: "cat_rb_nonveg_starters", name: "Non-Veg Starters & Tandoor", sortOrder: 2 },
  { id: "cat_rb_chowmein", name: "Chowmein & Noodles", sortOrder: 3 },
  { id: "cat_rb_soups", name: "Soups", sortOrder: 4 },
  { id: "cat_rb_veg_main", name: "Veg Main Course", sortOrder: 5 },
  { id: "cat_rb_nonveg_main", name: "Non-Veg Main Course", sortOrder: 6 },
  { id: "cat_rb_biryani", name: "Biryani Specials", sortOrder: 7 },
  { id: "cat_rb_rice", name: "Rice & Pulao", sortOrder: 8 },
  { id: "cat_rb_breads", name: "Tandoori Breads & Naan", sortOrder: 9 },
  { id: "cat_rb_rolls", name: "Rolls", sortOrder: 10 },
  { id: "cat_rb_salads", name: "Salads & Papads", sortOrder: 11 },
  { id: "cat_rb_raita", name: "Raitas", sortOrder: 12 },
  { id: "cat_rb_beverages", name: "Beverages", sortOrder: 13 },
  { id: "cat_rb_desserts", name: "Desserts", sortOrder: 14 },
];

/* ══════════════════════════════════════════════════════════════════════
   Menu Items Definition
   ══════════════════════════════════════════════════════════════════════ */

interface ItemDef {
  id: string;
  categoryId: string;
  name: string;
  description: string;
  isVeg: boolean;
  pricePaise: Paise;
  isPopular?: boolean;
  addOnGroups?: AddOnGroup[];
  sortOrder: number;
}

const ITEMS: ItemDef[] = [
  // ── 1. VEG STARTERS ──────────────────────────────────────────────────
  {
    id: "rb_veg_manchurian",
    categoryId: "cat_rb_veg_starters",
    name: "Veg Manchurian",
    description: "Crisp vegetable balls in spicy garlic soya sauce.",
    isVeg: true,
    pricePaise: R(80),
    addOnGroups: [portionGroup(R(80), R(160))],
    sortOrder: 1,
  },
  {
    id: "rb_gobi_manchurian",
    categoryId: "cat_rb_veg_starters",
    name: "Gobi Manchurian",
    description: "Batter fried cauliflower florets tossed in Manchurian glaze.",
    isVeg: true,
    pricePaise: R(160),
    sortOrder: 2,
  },
  {
    id: "rb_paneer_manchurian",
    categoryId: "cat_rb_veg_starters",
    name: "Paneer Manchurian",
    description: "Cottage cheese cubes tossed in spicy Manchurian gravy.",
    isVeg: true,
    pricePaise: R(220),
    sortOrder: 3,
  },
  {
    id: "rb_paneer_chilli",
    categoryId: "cat_rb_veg_starters",
    name: "Paneer Chilli",
    description: "Cottage cheese cubes tossed with capsicum, onion and chillies.",
    isVeg: true,
    pricePaise: R(120),
    isPopular: true,
    addOnGroups: [portionGroup(R(120), R(220))],
    sortOrder: 4,
  },
  {
    id: "rb_paneer_tikka",
    categoryId: "cat_rb_veg_starters",
    name: "Paneer Tikka",
    description: "Tandoor grilled marinated spiced paneer cubes.",
    isVeg: true,
    pricePaise: R(230),
    isPopular: true,
    sortOrder: 5,
  },
  {
    id: "rb_paneer_malai_tikka",
    categoryId: "cat_rb_veg_starters",
    name: "Paneer Malai Tikka",
    description: "Creamy cashew and cardamom marinated grilled cottage cheese.",
    isVeg: true,
    pricePaise: R(250),
    isPopular: true,
    sortOrder: 6,
  },
  {
    id: "rb_paneer_pakora",
    categoryId: "cat_rb_veg_starters",
    name: "Paneer Pakora",
    description: "Gram flour coated crispy golden paneer fritters.",
    isVeg: true,
    pricePaise: R(170),
    sortOrder: 7,
  },
  {
    id: "rb_veg_pakora",
    categoryId: "cat_rb_veg_starters",
    name: "Veg Pakora",
    description: "Assorted deep fried crispy vegetable pakoras.",
    isVeg: true,
    pricePaise: R(150),
    sortOrder: 8,
  },
  {
    id: "rb_onion_pakora",
    categoryId: "cat_rb_veg_starters",
    name: "Onion Pakora",
    description: "Crunchy sliced onion fritters with chaat masala.",
    isVeg: true,
    pricePaise: R(150),
    sortOrder: 9,
  },
  {
    id: "rb_mushroom_chilli",
    categoryId: "cat_rb_veg_starters",
    name: "Mushroom Chilli",
    description: "Fried fresh button mushrooms in spicy chilli glaze.",
    isVeg: true,
    pricePaise: R(230),
    sortOrder: 10,
  },
  {
    id: "rb_mushroom_manchurian",
    categoryId: "cat_rb_veg_starters",
    name: "Mushroom Manchurian",
    description: "Button mushrooms in Indo-Chinese dark soya sauce.",
    isVeg: true,
    pricePaise: R(230),
    sortOrder: 11,
  },
  {
    id: "rb_mushroom_crispy",
    categoryId: "cat_rb_veg_starters",
    name: "Mushroom Crispy",
    description: "Batter fried crunchy golden mushrooms.",
    isVeg: true,
    pricePaise: R(230),
    sortOrder: 12,
  },
  {
    id: "rb_babycorn_chilli",
    categoryId: "cat_rb_veg_starters",
    name: "Babycorn Chilli",
    description: "Crispy baby corn tossed in spicy chilli garlic sauce.",
    isVeg: true,
    pricePaise: R(230),
    sortOrder: 13,
  },
  {
    id: "rb_babycorn_manchurian",
    categoryId: "cat_rb_veg_starters",
    name: "Baby Corn Manchurian",
    description: "Tender baby corn in savoury Manchurian sauce.",
    isVeg: true,
    pricePaise: R(240),
    sortOrder: 14,
  },
  {
    id: "rb_babycorn_crispy",
    categoryId: "cat_rb_veg_starters",
    name: "Babycorn Crispy",
    description: "Deep fried crispy spiced baby corn fingers.",
    isVeg: true,
    pricePaise: R(230),
    sortOrder: 15,
  },
  {
    id: "rb_honey_potato_chilli",
    categoryId: "cat_rb_veg_starters",
    name: "Honey Potato Chilli",
    description: "Sweet and spicy glazed crispy potatoes with sesame.",
    isVeg: true,
    pricePaise: R(200),
    isPopular: true,
    sortOrder: 16,
  },
  {
    id: "rb_hara_bhara_kabab",
    categoryId: "cat_rb_veg_starters",
    name: "Hara Bhara Kabab (8 Pcs)",
    description: "Spinach, green pea and paneer spiced shallow fried patties.",
    isVeg: true,
    pricePaise: R(150),
    sortOrder: 17,
  },
  {
    id: "rb_corn_salt_pepper",
    categoryId: "cat_rb_veg_starters",
    name: "Corn Salt & Pepper",
    description: "Crispy fried sweet corn tossed with crushed black pepper.",
    isVeg: true,
    pricePaise: R(220),
    sortOrder: 18,
  },
  {
    id: "rb_veg_lollipop",
    categoryId: "cat_rb_veg_starters",
    name: "Veg Lollipop",
    description: "Spicy fried vegetable lollipops served with hot dip.",
    isVeg: true,
    pricePaise: R(150),
    addOnGroups: [portionGroup(R(150), R(250), "4 Pcs", "8 Pcs")],
    sortOrder: 19,
  },
  {
    id: "rb_cheese_ball",
    categoryId: "cat_rb_veg_starters",
    name: "Cheese Ball (8 Pcs)",
    description: "Mouth-melting crispy fried cheese stuffed balls.",
    isVeg: true,
    pricePaise: R(250),
    isPopular: true,
    sortOrder: 20,
  },
  {
    id: "rb_dahi_kabab",
    categoryId: "cat_rb_veg_starters",
    name: "Dahi Kabab (8 Pcs)",
    description: "Creamy spiced hung yogurt patties with crispy exterior.",
    isVeg: true,
    pricePaise: R(250),
    isPopular: true,
    sortOrder: 21,
  },
  {
    id: "rb_veg_sheek_kabab",
    categoryId: "cat_rb_veg_starters",
    name: "Veg Seekh Kabab (8 Pcs)",
    description: "Minced spiced vegetables skewered and char-grilled.",
    isVeg: true,
    pricePaise: R(250),
    sortOrder: 22,
  },

  // ── 2. NON-VEG STARTERS & TANDOOR ───────────────────────────────────
  {
    id: "rb_chicken_chilli_bone_boneless",
    categoryId: "cat_rb_nonveg_starters",
    name: "Chicken Chilli (8 Pcs)",
    description: "Indo-Chinese wok tossed spicy chicken with bell peppers.",
    isVeg: false,
    pricePaise: R(220),
    isPopular: true,
    addOnGroups: [portionGroup(R(220), R(250), "With Bone", "Boneless")],
    sortOrder: 1,
  },
  {
    id: "rb_chicken_manchurian_boneless",
    categoryId: "cat_rb_nonveg_starters",
    name: "Chicken Manchurian (Boneless)",
    description: "Boneless chicken dumplings in spicy dark soya garlic gravy.",
    isVeg: false,
    pricePaise: R(250),
    sortOrder: 2,
  },
  {
    id: "rb_chicken_lollipop",
    categoryId: "cat_rb_nonveg_starters",
    name: "Chicken Lollipop",
    description: "Frenched chicken drumettes deep fried with Indo-Chinese spices.",
    isVeg: false,
    pricePaise: R(180),
    isPopular: true,
    addOnGroups: [portionGroup(R(180), R(350), "Half (4 Pcs)", "Full (8 Pcs)")],
    sortOrder: 3,
  },
  {
    id: "rb_chicken_65_boneless",
    categoryId: "cat_rb_nonveg_starters",
    name: "Chicken 65 Boneless (8 Pcs)",
    description: "South Indian style spicy deep-fried chicken tossed with curry leaves.",
    isVeg: false,
    pricePaise: R(260),
    isPopular: true,
    sortOrder: 4,
  },
  {
    id: "rb_egg_pakora",
    categoryId: "cat_rb_nonveg_starters",
    name: "Egg Pakora",
    description: "Boiled egg halves dipped in spiced gram flour batter and fried.",
    isVeg: false,
    pricePaise: R(120),
    sortOrder: 5,
  },
  {
    id: "rb_egg_omlet_2_eggs",
    categoryId: "cat_rb_nonveg_starters",
    name: "Egg Omelette (2 Eggs)",
    description: "Fresh 2-egg omelette cooked with onions, tomatoes and green chillies.",
    isVeg: false,
    pricePaise: R(60),
    sortOrder: 6,
  },
  {
    id: "rb_fish_fry_rohu",
    categoryId: "cat_rb_nonveg_starters",
    name: "Fish Fry (Rohu Fish, 4 Pcs)",
    description: "Crispy shallow-fried fresh Rohu fish marinated in mustard and spices.",
    isVeg: false,
    pricePaise: R(200),
    isPopular: true,
    sortOrder: 7,
  },
  {
    id: "rb_fish_tikka",
    categoryId: "cat_rb_nonveg_starters",
    name: "Fish Tikka (4 Pcs)",
    description: "Tandoori grilled boneless fish morsels marinated in yogurt and spices.",
    isVeg: false,
    pricePaise: R(210),
    sortOrder: 8,
  },
  {
    id: "rb_chicken_cheese_ball",
    categoryId: "cat_rb_nonveg_starters",
    name: "Chicken Cheese Ball",
    description: "Crispy fried minced chicken balls oozing with melted cheese.",
    isVeg: false,
    pricePaise: R(150),
    addOnGroups: [portionGroup(R(150), R(270), "4 Pcs", "8 Pcs")],
    sortOrder: 9,
  },
  {
    id: "rb_chicken_tikka",
    categoryId: "cat_rb_nonveg_starters",
    name: "Chicken Tikka",
    description: "Charcoal grilled succulent boneless chicken tikka.",
    isVeg: false,
    pricePaise: R(180),
    isPopular: true,
    addOnGroups: [portionGroup(R(180), R(360), "4 Pcs", "8 Pcs")],
    sortOrder: 10,
  },
  {
    id: "rb_chicken_afghani",
    categoryId: "cat_rb_nonveg_starters",
    name: "Chicken Afghani",
    description: "Mild and creamy cashew marinade tandoor grilled chicken.",
    isVeg: false,
    pricePaise: R(200),
    isPopular: true,
    addOnGroups: [portionGroup(R(200), R(400), "4 Pcs", "8 Pcs")],
    sortOrder: 11,
  },
  {
    id: "rb_chicken_malai_tikka",
    categoryId: "cat_rb_nonveg_starters",
    name: "Chicken Malai Tikka",
    description: "Rich cream and cheese glazed boneless chicken tikkas.",
    isVeg: false,
    pricePaise: R(220),
    isPopular: true,
    addOnGroups: [portionGroup(R(220), R(420), "4 Pcs", "8 Pcs")],
    sortOrder: 12,
  },
  {
    id: "rb_chicken_tandoori",
    categoryId: "cat_rb_nonveg_starters",
    name: "Chicken Tandoori",
    description: "Classic royal tandoori roasted whole chicken with mint dip.",
    isVeg: false,
    pricePaise: R(200),
    isPopular: true,
    addOnGroups: [portionGroup(R(200), R(360), "4 Pcs (Half)", "8 Pcs (Full)")],
    sortOrder: 13,
  },
  {
    id: "rb_reshmi_kabab",
    categoryId: "cat_rb_nonveg_starters",
    name: "Reshmi Kabab",
    description: "Silky soft skewered chicken kababs spiced with royal herbs.",
    isVeg: false,
    pricePaise: R(280),
    sortOrder: 14,
  },
  {
    id: "rb_chicken_leg_kabab",
    categoryId: "cat_rb_nonveg_starters",
    name: "Chicken Leg Kabab (2 Pcs)",
    description: "Tandoori char-grilled whole chicken drumsticks.",
    isVeg: false,
    pricePaise: R(270),
    isPopular: true,
    sortOrder: 15,
  },

  // ── 3. CHOWMEIN & NOODLES ────────────────────────────────────────────
  {
    id: "rb_veg_chowmein",
    categoryId: "cat_rb_chowmein",
    name: "Veg Chowmein",
    description: "Wok tossed noodles with shredded vegetables.",
    isVeg: true,
    pricePaise: R(120),
    sortOrder: 1,
  },
  {
    id: "rb_mix_veg_chowmein",
    categoryId: "cat_rb_chowmein",
    name: "Mix Veg Chowmein",
    description: "Loaded noodles with paneer, mushrooms and baby corn.",
    isVeg: true,
    pricePaise: R(160),
    sortOrder: 2,
  },
  {
    id: "rb_paneer_chowmein",
    categoryId: "cat_rb_chowmein",
    name: "Paneer Chowmein",
    description: "Stir fried noodles tossed with fresh paneer cubes.",
    isVeg: true,
    pricePaise: R(150),
    sortOrder: 3,
  },
  {
    id: "rb_mushroom_chowmein",
    categoryId: "cat_rb_chowmein",
    name: "Mushroom Chowmein",
    description: "Noodles with fresh sliced button mushrooms.",
    isVeg: true,
    pricePaise: R(150),
    sortOrder: 4,
  },
  {
    id: "rb_babycorn_chowmein",
    categoryId: "cat_rb_chowmein",
    name: "Babycorn Chowmein",
    description: "Stir-fried noodles with crunchy baby corn pieces.",
    isVeg: true,
    pricePaise: R(150),
    sortOrder: 5,
  },
  {
    id: "rb_egg_chowmein",
    categoryId: "cat_rb_chowmein",
    name: "Egg Chowmein",
    description: "Scrambled egg noodles tossed with onions and spices.",
    isVeg: false,
    pricePaise: R(140),
    sortOrder: 6,
  },
  {
    id: "rb_chicken_chowmein",
    categoryId: "cat_rb_chowmein",
    name: "Chicken Chowmein",
    description: "Indo-Chinese wok tossed noodles with seasoned chicken.",
    isVeg: false,
    pricePaise: R(170),
    isPopular: true,
    sortOrder: 7,
  },
  {
    id: "rb_mix_chicken_chowmein",
    categoryId: "cat_rb_chowmein",
    name: "Mix Chicken Chowmein",
    description: "Loaded combination of chicken, scrambled egg and veggies.",
    isVeg: false,
    pricePaise: R(200),
    isPopular: true,
    sortOrder: 8,
  },

  // ── 4. SOUPS ─────────────────────────────────────────────────────────
  {
    id: "rb_veg_hot_sour_soup",
    categoryId: "cat_rb_soups",
    name: "Veg Hot & Sour Soup",
    description: "Spicy and tangy vegetable broth with black pepper.",
    isVeg: true,
    pricePaise: R(70),
    sortOrder: 1,
  },
  {
    id: "rb_veg_sweetcorn_soup",
    categoryId: "cat_rb_soups",
    name: "Veg Sweetcorn Soup",
    description: "Comforting creamy golden corn soup.",
    isVeg: true,
    pricePaise: R(70),
    sortOrder: 2,
  },
  {
    id: "rb_veg_manchow_soup",
    categoryId: "cat_rb_soups",
    name: "Veg Manchow Soup",
    description: "Spicy garlic soup topped with crispy fried noodles.",
    isVeg: true,
    pricePaise: R(70),
    isPopular: true,
    sortOrder: 3,
  },
  {
    id: "rb_tomato_soup",
    categoryId: "cat_rb_soups",
    name: "Tomato Soup",
    description: "Classic rich tomato soup with herb butter croutons.",
    isVeg: true,
    pricePaise: R(60),
    sortOrder: 4,
  },
  {
    id: "rb_chicken_hot_sour_soup",
    categoryId: "cat_rb_soups",
    name: "Chicken Hot & Sour Soup",
    description: "Fiery spicy chicken soup with shredded vegetables.",
    isVeg: false,
    pricePaise: R(90),
    sortOrder: 5,
  },
  {
    id: "rb_chicken_sweetcorn_soup",
    categoryId: "cat_rb_soups",
    name: "Chicken Sweetcorn Soup",
    description: "Rich sweet corn and tender chicken broth.",
    isVeg: false,
    pricePaise: R(90),
    sortOrder: 6,
  },
  {
    id: "rb_chicken_manchow_soup",
    categoryId: "cat_rb_soups",
    name: "Chicken Manchow Soup",
    description: "Spicy chicken soup served with crunchy fried noodles.",
    isVeg: false,
    pricePaise: R(90),
    isPopular: true,
    sortOrder: 7,
  },

  // ── 5. VEG MAIN COURSE ───────────────────────────────────────────────
  {
    id: "rb_aloo_jeera",
    categoryId: "cat_rb_veg_main",
    name: "Aloo Jeera",
    description: "Potatoes tossed with roasted cumin seeds and turmeric.",
    isVeg: true,
    pricePaise: R(130),
    sortOrder: 1,
  },
  {
    id: "rb_aloo_matar",
    categoryId: "cat_rb_veg_main",
    name: "Aloo Matar",
    description: "Homestyle potato and green peas curry.",
    isVeg: true,
    pricePaise: R(160),
    sortOrder: 2,
  },
  {
    id: "rb_aloo_gobi",
    categoryId: "cat_rb_veg_main",
    name: "Aloo Gobi",
    description: "Cauliflower and potato curry cooked with ginger and spices.",
    isVeg: true,
    pricePaise: R(160),
    sortOrder: 3,
  },
  {
    id: "rb_banarasi_dum_aloo",
    categoryId: "cat_rb_veg_main",
    name: "Banarasi Dum Aloo",
    description: "Stuffed whole baby potatoes in rich spiced tomato cashew gravy.",
    isVeg: true,
    pricePaise: R(200),
    isPopular: true,
    sortOrder: 4,
  },
  {
    id: "rb_aloo_do_pyaza",
    categoryId: "cat_rb_veg_main",
    name: "Aloo Do Pyaza",
    description: "Potato curry cooked with caramelised pearl onions.",
    isVeg: true,
    pricePaise: R(160),
    sortOrder: 5,
  },
  {
    id: "rb_veg_kofta",
    categoryId: "cat_rb_veg_main",
    name: "Veg Kofta",
    description: "Crispy vegetable dumplings in spiced aromatic curry.",
    isVeg: true,
    pricePaise: R(240),
    sortOrder: 6,
  },
  {
    id: "rb_malai_kofta",
    categoryId: "cat_rb_veg_main",
    name: "Malai Kofta",
    description: "Mouth-melting paneer and mawa dumplings in rich sweet-savory gravy.",
    isVeg: true,
    pricePaise: R(270),
    isPopular: true,
    sortOrder: 7,
  },
  {
    id: "rb_mix_veg",
    categoryId: "cat_rb_veg_main",
    name: "Mix Veg",
    description: "Seasonal garden vegetables cooked in North Indian curry sauce.",
    isVeg: true,
    pricePaise: R(210),
    sortOrder: 8,
  },
  {
    id: "rb_paneer_masala",
    categoryId: "cat_rb_veg_main",
    name: "Paneer Masala",
    description: "Cottage cheese cubes in aromatic spicy onion-tomato gravy.",
    isVeg: true,
    pricePaise: R(230),
    sortOrder: 9,
  },
  {
    id: "rb_paneer_butter_masala",
    categoryId: "cat_rb_veg_main",
    name: "Paneer Butter Masala",
    description: "All-time favorite paneer in creamy buttery makhani sauce.",
    isVeg: true,
    pricePaise: R(250),
    isPopular: true,
    sortOrder: 10,
  },
  {
    id: "rb_paneer_tikka_masala",
    categoryId: "cat_rb_veg_main",
    name: "Paneer Tikka Masala",
    description: "Charcoal grilled paneer tikkas simmered in spicy masala gravy.",
    isVeg: true,
    pricePaise: R(270),
    isPopular: true,
    sortOrder: 11,
  },
  {
    id: "rb_paneer_do_pyaza",
    categoryId: "cat_rb_veg_main",
    name: "Paneer Do Pyaza",
    description: "Paneer cooked with double the onions in rich masala.",
    isVeg: true,
    pricePaise: R(250),
    sortOrder: 12,
  },
  {
    id: "rb_royal_bihar_special_paneer",
    categoryId: "cat_rb_veg_main",
    name: "The Royal Bihar Special Paneer",
    description: "Chef's signature royal paneer dish prepared with secret spices.",
    isVeg: true,
    pricePaise: R(350),
    isPopular: true,
    sortOrder: 13,
  },
  {
    id: "rb_shahi_paneer",
    categoryId: "cat_rb_veg_main",
    name: "Shahi Paneer",
    description: "Royal cottage cheese curry in rich white cashew gravy.",
    isVeg: true,
    pricePaise: R(300),
    isPopular: true,
    sortOrder: 14,
  },
  {
    id: "rb_paneer_punjabi",
    categoryId: "cat_rb_veg_main",
    name: "Paneer Punjabi",
    description: "Spicy dhaba style paneer in hearty thick gravy.",
    isVeg: true,
    pricePaise: R(280),
    sortOrder: 15,
  },
  {
    id: "rb_paneer_kofta",
    categoryId: "cat_rb_veg_main",
    name: "Paneer Kofta",
    description: "Soft paneer dumplings simmered in luscious curry.",
    isVeg: true,
    pricePaise: R(270),
    sortOrder: 16,
  },
  {
    id: "rb_paneer_kadai",
    categoryId: "cat_rb_veg_main",
    name: "Paneer Kadai",
    description: "Paneer cooked in freshly ground kadai spices and bell peppers.",
    isVeg: true,
    pricePaise: R(260),
    isPopular: true,
    sortOrder: 17,
  },
  {
    id: "rb_matar_paneer",
    categoryId: "cat_rb_veg_main",
    name: "Matar Paneer",
    description: "Classic cottage cheese and green peas in spiced onion gravy.",
    isVeg: true,
    pricePaise: R(210),
    sortOrder: 18,
  },
  {
    id: "rb_palak_paneer",
    categoryId: "cat_rb_veg_main",
    name: "Palak Paneer",
    description: "Paneer cubes in vibrant fresh spinach puree with garlic.",
    isVeg: true,
    pricePaise: R(220),
    sortOrder: 19,
  },
  {
    id: "rb_veg_navratan_korma",
    categoryId: "cat_rb_veg_main",
    name: "Veg Navratan Korma",
    description: "Nine gem vegetables, fruits and nuts in sweet creamy gravy.",
    isVeg: true,
    pricePaise: R(280),
    sortOrder: 20,
  },
  {
    id: "rb_mushroom_masala",
    categoryId: "cat_rb_veg_main",
    name: "Mushroom Masala",
    description: "Fresh button mushrooms in rich spicy gravy.",
    isVeg: true,
    pricePaise: R(240),
    sortOrder: 21,
  },
  {
    id: "rb_mushroom_butter_masala",
    categoryId: "cat_rb_veg_main",
    name: "Mushroom Butter Masala",
    description: "Mushrooms in smooth buttery tomato gravy.",
    isVeg: true,
    pricePaise: R(250),
    sortOrder: 22,
  },
  {
    id: "rb_mushroom_kadai",
    categoryId: "cat_rb_veg_main",
    name: "Mushroom Kadai",
    description: "Wok cooked mushrooms with coriander seeds and capsicum.",
    isVeg: true,
    pricePaise: R(250),
    sortOrder: 23,
  },
  {
    id: "rb_matar_mushroom",
    categoryId: "cat_rb_veg_main",
    name: "Matar Mushroom",
    description: "Tender green peas and mushrooms in fragrant curry.",
    isVeg: true,
    pricePaise: R(230),
    sortOrder: 24,
  },
  {
    id: "rb_mushroom_paneer_masala",
    categoryId: "cat_rb_veg_main",
    name: "Mushroom Paneer Masala",
    description: "Combination of paneer and mushroom in thick masala.",
    isVeg: true,
    pricePaise: R(250),
    sortOrder: 25,
  },
  {
    id: "rb_mushroom_do_pyaza",
    categoryId: "cat_rb_veg_main",
    name: "Mushroom Do Pyaza",
    description: "Mushrooms cooked with diced crunchy onions.",
    isVeg: true,
    pricePaise: R(250),
    sortOrder: 26,
  },
  {
    id: "rb_mushroom_dehati",
    categoryId: "cat_rb_veg_main",
    name: "Mushroom Dehati",
    description: "Rustic village style spicy Bihari mushroom curry.",
    isVeg: true,
    pricePaise: R(250),
    isPopular: true,
    sortOrder: 27,
  },
  {
    id: "rb_dal_makhani",
    categoryId: "cat_rb_veg_main",
    name: "Dal Makhani",
    description: "Slow simmered black lentils in butter and cream overnight.",
    isVeg: true,
    pricePaise: R(160),
    isPopular: true,
    sortOrder: 28,
  },
  {
    id: "rb_dal_fry",
    categoryId: "cat_rb_veg_main",
    name: "Dal Fry",
    description: "Yellow toor dal tempered with cumin, garlic and ghee.",
    isVeg: true,
    pricePaise: R(90),
    sortOrder: 29,
  },
  {
    id: "rb_dal_tadka",
    categoryId: "cat_rb_veg_main",
    name: "Dal Tadka",
    description: "Yellow lentils finished with double desi ghee garlic tadka.",
    isVeg: true,
    pricePaise: R(120),
    isPopular: true,
    sortOrder: 30,
  },
  {
    id: "rb_dal_makkhan",
    categoryId: "cat_rb_veg_main",
    name: "Dal Makkhan",
    description: "Special butter laden yellow dal.",
    isVeg: true,
    pricePaise: R(110),
    sortOrder: 31,
  },
  {
    id: "rb_babycorn_masala",
    categoryId: "cat_rb_veg_main",
    name: "Babycorn Masala",
    description: "Baby corn in rich spicy North Indian gravy.",
    isVeg: true,
    pricePaise: R(250),
    sortOrder: 32,
  },
  {
    id: "rb_babycorn_kadai",
    categoryId: "cat_rb_veg_main",
    name: "Babycorn Kadai",
    description: "Kadai spiced crunchy baby corn curry.",
    isVeg: true,
    pricePaise: R(250),
    sortOrder: 33,
  },
  {
    id: "rb_paneer_lababdar",
    categoryId: "cat_rb_veg_main",
    name: "Paneer Lababdar",
    description: "Grated and cubed cottage cheese in rich creamy gravy.",
    isVeg: true,
    pricePaise: R(280),
    isPopular: true,
    sortOrder: 34,
  },
  {
    id: "rb_mushroom_paneer_bahar",
    categoryId: "cat_rb_veg_main",
    name: "Mushroom Paneer Bahar",
    description: "Royal blend of mushrooms and paneer in saffron gravy.",
    isVeg: true,
    pricePaise: R(290),
    sortOrder: 35,
  },
  {
    id: "rb_matar_methi_malai",
    categoryId: "cat_rb_veg_main",
    name: "Matar Methi Malai",
    description: "Green peas and fenugreek leaves in rich white cream gravy.",
    isVeg: true,
    pricePaise: R(240),
    sortOrder: 36,
  },
  {
    id: "rb_mushroom_matar_methi_malai",
    categoryId: "cat_rb_veg_main",
    name: "Mushroom Matar Methi Malai",
    description: "Mushrooms, peas and methi simmered in malai sauce.",
    isVeg: true,
    pricePaise: R(260),
    sortOrder: 37,
  },
  {
    id: "rb_paneer_pasanda",
    categoryId: "cat_rb_veg_main",
    name: "Paneer Pasanda",
    description: "Stuffed paneer sandwiches shallow fried in rich royal gravy.",
    isVeg: true,
    pricePaise: R(250),
    sortOrder: 38,
  },
  {
    id: "rb_palak_corn",
    categoryId: "cat_rb_veg_main",
    name: "Palak Corn",
    description: "Sweet golden corn in freshly pureed garlicky spinach gravy.",
    isVeg: true,
    pricePaise: R(250),
    sortOrder: 39,
  },
  {
    id: "rb_paneer_dehati",
    categoryId: "cat_rb_veg_main",
    name: "Paneer Dehati",
    description: "Bihari village style rustic spicy paneer curry.",
    isVeg: true,
    pricePaise: R(300),
    isPopular: true,
    sortOrder: 40,
  },
  {
    id: "rb_paneer_bharta",
    categoryId: "cat_rb_veg_main",
    name: "Paneer Bharta",
    description: "Spiced scrambled cottage cheese with onions, tomatoes and coriander.",
    isVeg: true,
    pricePaise: R(260),
    sortOrder: 41,
  },

  // ── 6. NON-VEG MAIN COURSE ───────────────────────────────────────────
  {
    id: "rb_chicken_curry",
    categoryId: "cat_rb_nonveg_main",
    name: "Chicken Curry (4 Pcs)",
    description: "Traditional spicy homestyle chicken curry.",
    isVeg: false,
    pricePaise: R(250),
    isPopular: true,
    sortOrder: 1,
  },
  {
    id: "rb_chicken_masala",
    categoryId: "cat_rb_nonveg_main",
    name: "Chicken Masala (4 Pcs)",
    description: "Chicken cooked in thick spicy onion-tomato gravy.",
    isVeg: false,
    pricePaise: R(260),
    sortOrder: 2,
  },
  {
    id: "rb_chicken_butter_masala",
    categoryId: "cat_rb_nonveg_main",
    name: "Chicken Butter Masala (4 Pcs)",
    description: "Tender chicken pieces in rich creamy buttery makhani gravy.",
    isVeg: false,
    pricePaise: R(290),
    isPopular: true,
    sortOrder: 3,
  },
  {
    id: "rb_chicken_leg_masala",
    categoryId: "cat_rb_nonveg_main",
    name: "Chicken Leg Masala",
    description: "Whole chicken leg cooked in robust royal masala gravy.",
    isVeg: false,
    pricePaise: R(320),
    isPopular: true,
    sortOrder: 4,
  },
  {
    id: "rb_chicken_tikka_masala",
    categoryId: "cat_rb_nonveg_main",
    name: "Chicken Tikka Masala (8 Pcs)",
    description: "Tandoori chicken tikkas simmered in spicy royal curry.",
    isVeg: false,
    pricePaise: R(300),
    isPopular: true,
    sortOrder: 5,
  },
  {
    id: "rb_chicken_tikka_butter_masala",
    categoryId: "cat_rb_nonveg_main",
    name: "Chicken Tikka Butter Masala (8 Pcs)",
    description: "Smoky chicken tikkas in velvety buttery tomato gravy.",
    isVeg: false,
    pricePaise: R(320),
    isPopular: true,
    sortOrder: 6,
  },
  {
    id: "rb_chicken_do_pyaza",
    categoryId: "cat_rb_nonveg_main",
    name: "Chicken Do Pyaza",
    description: "Chicken curry with sautéed diced onions and spices.",
    isVeg: false,
    pricePaise: R(260),
    sortOrder: 7,
  },
  {
    id: "rb_chicken_kadai",
    categoryId: "cat_rb_nonveg_main",
    name: "Chicken Kadai",
    description: "Chicken wok-cooked in crushed coriander, dry chillies and capsicum.",
    isVeg: false,
    pricePaise: R(270),
    sortOrder: 8,
  },
  {
    id: "rb_chicken_punjabi",
    categoryId: "cat_rb_nonveg_main",
    name: "Chicken Punjabi",
    description: "Robust spicy Punjabi style chicken curry.",
    isVeg: false,
    pricePaise: R(300),
    sortOrder: 9,
  },
  {
    id: "rb_chicken_dehati",
    categoryId: "cat_rb_nonveg_main",
    name: "Chicken Dehati",
    description: "Signature authentic Bihari rustic claypot chicken curry.",
    isVeg: false,
    pricePaise: R(300),
    isPopular: true,
    addOnGroups: [portionGroup(R(300), R(600))],
    sortOrder: 10,
  },
  {
    id: "rb_chicken_handi",
    categoryId: "cat_rb_nonveg_main",
    name: "Chicken Handi (4 Pcs)",
    description: "Slow-cooked handi chicken in fragrant whole spices.",
    isVeg: false,
    pricePaise: R(290),
    isPopular: true,
    sortOrder: 11,
  },
  {
    id: "rb_murg_mussallam",
    categoryId: "cat_rb_nonveg_main",
    name: "Murg Mussallam",
    description: "Grand royal Mughlai preparation of chicken cooked with rich spices and eggs.",
    isVeg: false,
    pricePaise: R(650),
    isPopular: true,
    sortOrder: 12,
  },
  {
    id: "rb_chicken_pasanda",
    categoryId: "cat_rb_nonveg_main",
    name: "Chicken Pasanda (8 Pcs)",
    description: "Mild Mughlai chicken curry cooked in almond and cream sauce.",
    isVeg: false,
    pricePaise: R(270),
    sortOrder: 13,
  },
  {
    id: "rb_chicken_korma",
    categoryId: "cat_rb_nonveg_main",
    name: "Chicken Korma",
    description: "Royal slow cooked chicken in cashew-yogurt gravy.",
    isVeg: false,
    pricePaise: R(320),
    sortOrder: 14,
  },
  {
    id: "rb_chicken_bharta",
    categoryId: "cat_rb_nonveg_main",
    name: "Chicken Bharta",
    description: "Minced shredded chicken cooked with egg in rich creamy gravy.",
    isVeg: false,
    pricePaise: R(340),
    isPopular: true,
    sortOrder: 15,
  },
  {
    id: "rb_chicken_tandoor_gravy",
    categoryId: "cat_rb_nonveg_main",
    name: "Chicken Tandoor Gravy",
    description: "Tandoori chicken pieces in rich spicy masala gravy.",
    isVeg: false,
    pricePaise: R(200),
    addOnGroups: [portionGroup(R(200), R(320))],
    sortOrder: 16,
  },
  {
    id: "rb_chicken_boneless_butter_masala",
    categoryId: "cat_rb_nonveg_main",
    name: "Chicken Boneless Butter Masala",
    description: "Boneless chicken chunks in silky buttery tomato gravy.",
    isVeg: false,
    pricePaise: R(180),
    isPopular: true,
    addOnGroups: [portionGroup(R(180), R(300))],
    sortOrder: 17,
  },
  {
    id: "rb_chicken_lababdar",
    categoryId: "cat_rb_nonveg_main",
    name: "Chicken Lababdar",
    description: "Creamy Mughlai chicken in tomato, butter and grated egg gravy.",
    isVeg: false,
    pricePaise: R(180),
    addOnGroups: [portionGroup(R(180), R(320))],
    sortOrder: 18,
  },
  {
    id: "rb_chicken_royal_bihar_special",
    categoryId: "cat_rb_nonveg_main",
    name: "Chicken The Royal Bihar Special",
    description: "Chef's pride royal special chicken preparation.",
    isVeg: false,
    pricePaise: R(350),
    isPopular: true,
    addOnGroups: [portionGroup(R(350), R(650))],
    sortOrder: 19,
  },
  {
    id: "rb_mutton_stew",
    categoryId: "cat_rb_nonveg_main",
    name: "Mutton Stew (4 Pcs)",
    description: "Traditional Bihari mutton stew cooked with whole spices and shallots.",
    isVeg: false,
    pricePaise: R(350),
    isPopular: true,
    sortOrder: 20,
  },
  {
    id: "rb_mutton_rogan_josh",
    categoryId: "cat_rb_nonveg_main",
    name: "Mutton Rogan Josh",
    description: "Kashmiri style aromatic slow-cooked tender mutton curry.",
    isVeg: false,
    pricePaise: R(350),
    isPopular: true,
    sortOrder: 21,
  },
  {
    id: "rb_mutton_handi_1kg",
    categoryId: "cat_rb_nonveg_main",
    name: "Mutton Handi (1 Kg)",
    description: "Famous Champaran style sealed earthen handi slow-cooked mutton.",
    isVeg: false,
    pricePaise: R(1100),
    isPopular: true,
    sortOrder: 22,
  },
  {
    id: "rb_fish_curry_rohu",
    categoryId: "cat_rb_nonveg_main",
    name: "Fish Curry (Rohu Fish, 4 Pcs)",
    description: "Traditional mustard-based Bihari fish curry.",
    isVeg: false,
    pricePaise: R(220),
    sortOrder: 23,
  },
  {
    id: "rb_egg_curry",
    categoryId: "cat_rb_nonveg_main",
    name: "Egg Curry",
    description: "Boiled fried eggs in spicy North Indian curry.",
    isVeg: false,
    pricePaise: R(90),
    addOnGroups: [portionGroup(R(90), R(150), "2 Eggs", "4 Eggs")],
    sortOrder: 24,
  },
  {
    id: "rb_egg_masala_2pcs",
    categoryId: "cat_rb_nonveg_main",
    name: "Egg Masala (2 Pcs)",
    description: "Double boiled eggs cooked in thick onion-tomato masala.",
    isVeg: false,
    pricePaise: R(130),
    sortOrder: 25,
  },
  {
    id: "rb_egg_butter_masala_2pcs",
    categoryId: "cat_rb_nonveg_main",
    name: "Egg Butter Masala (2 Pcs)",
    description: "Eggs simmered in creamy makhani butter gravy.",
    isVeg: false,
    pricePaise: R(150),
    sortOrder: 26,
  },

  // ── 7. BIRYANI SPECIALS ──────────────────────────────────────────────
  {
    id: "rb_veg_biryani",
    categoryId: "cat_rb_biryani",
    name: "Veg Biryani",
    description: "Fragrant basmati rice layered with spiced vegetables and herbs.",
    isVeg: true,
    pricePaise: R(160),
    sortOrder: 1,
  },
  {
    id: "rb_paneer_biryani",
    categoryId: "cat_rb_biryani",
    name: "Paneer Biryani",
    description: "Basmati rice cooked with marinated paneer tikkas and saffron.",
    isVeg: true,
    pricePaise: R(210),
    sortOrder: 2,
  },
  {
    id: "rb_mushroom_biryani",
    categoryId: "cat_rb_biryani",
    name: "Mushroom Biryani",
    description: "Aromatic dum biryani cooked with button mushrooms and spices.",
    isVeg: true,
    pricePaise: R(210),
    sortOrder: 3,
  },
  {
    id: "rb_chicken_masala_biryani",
    categoryId: "cat_rb_biryani",
    name: "Chicken Masala Biryani",
    description: "Spiced dum biryani layered with succulent chicken pieces.",
    isVeg: false,
    pricePaise: R(240),
    isPopular: true,
    sortOrder: 4,
  },
  {
    id: "rb_hyderabadi_chicken_biryani",
    categoryId: "cat_rb_biryani",
    name: "Hyderabadi Chicken Biryani",
    description: "Authentic spicy Hyderabadi dum biryani cooked on slow charcoal fire.",
    isVeg: false,
    pricePaise: R(280),
    isPopular: true,
    sortOrder: 5,
  },
  {
    id: "rb_hyderabadi_egg_biryani",
    categoryId: "cat_rb_biryani",
    name: "Hyderabadi Egg Biryani",
    description: "Hyderabadi dum rice cooked with spicy masala eggs.",
    isVeg: false,
    pricePaise: R(160),
    sortOrder: 6,
  },

  // ── 8. RICE & PULAO ──────────────────────────────────────────────────
  {
    id: "rb_plain_rice",
    categoryId: "cat_rb_rice",
    name: "Plain Rice",
    description: "Steamed long grain basmati rice.",
    isVeg: true,
    pricePaise: R(40),
    addOnGroups: [portionGroup(R(40), R(80))],
    sortOrder: 1,
  },
  {
    id: "rb_jeera_rice",
    categoryId: "cat_rb_rice",
    name: "Jeera Rice",
    description: "Fragrant basmati rice tempered with ghee and cumin seeds.",
    isVeg: true,
    pricePaise: R(50),
    addOnGroups: [portionGroup(R(50), R(100))],
    sortOrder: 2,
  },
  {
    id: "rb_veg_fried_rice",
    categoryId: "cat_rb_rice",
    name: "Veg Fried Rice",
    description: "Wok tossed basmati rice with finely diced vegetables.",
    isVeg: true,
    pricePaise: R(120),
    sortOrder: 3,
  },
  {
    id: "rb_mushroom_fried_rice",
    categoryId: "cat_rb_rice",
    name: "Mushroom Fried Rice",
    description: "Fried rice with button mushrooms and spring onions.",
    isVeg: true,
    pricePaise: R(150),
    sortOrder: 4,
  },
  {
    id: "rb_mix_nonveg_fried_rice",
    categoryId: "cat_rb_rice",
    name: "Mix Non-Veg Fried Rice",
    description: "Special fried rice loaded with chicken, egg and veggies.",
    isVeg: false,
    pricePaise: R(200),
    isPopular: true,
    sortOrder: 5,
  },
  {
    id: "rb_chicken_fried_rice",
    categoryId: "cat_rb_rice",
    name: "Chicken Fried Rice",
    description: "Classic fried rice tossed with shredded chicken.",
    isVeg: false,
    pricePaise: R(170),
    sortOrder: 6,
  },
  {
    id: "rb_veg_pulao",
    categoryId: "cat_rb_rice",
    name: "Veg Pulao",
    description: "Fragrant basmati pulao with green peas and whole spices.",
    isVeg: true,
    pricePaise: R(160),
    sortOrder: 7,
  },
  {
    id: "rb_veg_navratan_pulao",
    categoryId: "cat_rb_rice",
    name: "Veg Navratan Pulao",
    description: "Sweet and savory royal pulao with dry fruits and paneer.",
    isVeg: true,
    pricePaise: R(210),
    sortOrder: 8,
  },
  {
    id: "rb_kaju_pulao_special",
    categoryId: "cat_rb_rice",
    name: "The Royal Bihar Special Kaju Pulao",
    description: "Signature basmati pulao generously garnished with roasted cashews.",
    isVeg: true,
    pricePaise: R(220),
    isPopular: true,
    sortOrder: 9,
  },

  // ── 9. TANDOORI BREADS & NAAN ─────────────────────────────────────────
  {
    id: "rb_tandoori_roti",
    categoryId: "cat_rb_breads",
    name: "Tandoori Roti",
    description: "Whole wheat bread baked in traditional clay tandoor.",
    isVeg: true,
    pricePaise: R(15),
    sortOrder: 1,
  },
  {
    id: "rb_tandoori_butter_roti",
    categoryId: "cat_rb_breads",
    name: "Tandoori Butter Roti",
    description: "Tandoori roti brushed with melted butter.",
    isVeg: true,
    pricePaise: R(18),
    isPopular: true,
    sortOrder: 2,
  },
  {
    id: "rb_plain_naan",
    categoryId: "cat_rb_breads",
    name: "Plain Naan",
    description: "Soft leavened refined flour flatbread.",
    isVeg: true,
    pricePaise: R(45),
    sortOrder: 3,
  },
  {
    id: "rb_butter_naan",
    categoryId: "cat_rb_breads",
    name: "Butter Naan",
    description: "Soft tandoori naan brushed generously with butter.",
    isVeg: true,
    pricePaise: R(50),
    isPopular: true,
    sortOrder: 4,
  },
  {
    id: "rb_veg_stuffed_naan",
    categoryId: "cat_rb_breads",
    name: "Veg Stuffed Naan",
    description: "Naan stuffed with spiced minced vegetables.",
    isVeg: true,
    pricePaise: R(70),
    sortOrder: 5,
  },
  {
    id: "rb_garlic_stuffed_naan",
    categoryId: "cat_rb_breads",
    name: "Garlic Stuffed Naan",
    description: "Naan topped with roasted garlic and coriander.",
    isVeg: true,
    pricePaise: R(70),
    isPopular: true,
    sortOrder: 6,
  },
  {
    id: "rb_paneer_stuffed_naan",
    categoryId: "cat_rb_breads",
    name: "Paneer Stuffed Naan",
    description: "Naan stuffed with seasoned grated cottage cheese.",
    isVeg: true,
    pricePaise: R(80),
    isPopular: true,
    sortOrder: 7,
  },
  {
    id: "rb_missi_roti",
    categoryId: "cat_rb_breads",
    name: "Missi Roti",
    description: "Spiced gram flour and whole wheat flatbread.",
    isVeg: true,
    pricePaise: R(50),
    sortOrder: 8,
  },
  {
    id: "rb_lachha_paratha",
    categoryId: "cat_rb_breads",
    name: "Lachha Paratha",
    description: "Multi-layered crispy tandoori flaky paratha.",
    isVeg: true,
    pricePaise: R(50),
    sortOrder: 9,
  },
  {
    id: "rb_paneer_stuffed_paratha",
    categoryId: "cat_rb_breads",
    name: "Paneer Stuffed Paratha",
    description: "Tandoori paratha stuffed with spicy paneer.",
    isVeg: true,
    pricePaise: R(70),
    sortOrder: 10,
  },
  {
    id: "rb_aloo_paratha",
    categoryId: "cat_rb_breads",
    name: "Aloo Paratha",
    description: "Stuffed with spiced mashed potatoes.",
    isVeg: true,
    pricePaise: R(50),
    sortOrder: 11,
  },
  {
    id: "rb_gobi_paratha",
    categoryId: "cat_rb_breads",
    name: "Gobi Paratha",
    description: "Stuffed with seasoned grated cauliflower.",
    isVeg: true,
    pricePaise: R(50),
    sortOrder: 12,
  },
  {
    id: "rb_butter_plain_paratha",
    categoryId: "cat_rb_breads",
    name: "Butter Plain Paratha",
    description: "Simple buttered flatbread.",
    isVeg: true,
    pricePaise: R(20),
    sortOrder: 13,
  },
  {
    id: "rb_rumali_roti",
    categoryId: "cat_rb_breads",
    name: "Rumali Roti",
    description: "Ultra thin handkerchief flatbread.",
    isVeg: true,
    pricePaise: R(60),
    sortOrder: 14,
  },

  // ── 10. ROLLS ────────────────────────────────────────────────────────
  {
    id: "rb_veg_paneer_roll",
    categoryId: "cat_rb_rolls",
    name: "Veg Roll / Paneer Roll",
    description: "Crisp flaky paratha roll filled with seasoned vegetables or paneer.",
    isVeg: true,
    pricePaise: R(50),
    addOnGroups: [portionGroup(R(50), R(80), "Veg Roll", "Paneer Roll")],
    sortOrder: 1,
  },
  {
    id: "rb_paneer_tikka_roll",
    categoryId: "cat_rb_rolls",
    name: "Paneer Tikka Roll",
    description: "Tandoori grilled paneer tikkas with mint mayo.",
    isVeg: true,
    pricePaise: R(90),
    isPopular: true,
    sortOrder: 2,
  },
  {
    id: "rb_veg_mix_roll",
    categoryId: "cat_rb_rolls",
    name: "Veg Mix Roll",
    description: "Loaded mixed vegetable and corn roll.",
    isVeg: true,
    pricePaise: R(90),
    sortOrder: 3,
  },
  {
    id: "rb_egg_roll_single_double",
    categoryId: "cat_rb_rolls",
    name: "Egg Roll",
    description: "Classic street roll with egg, sliced onions and tangy sauce.",
    isVeg: false,
    pricePaise: R(60),
    isPopular: true,
    addOnGroups: [portionGroup(R(60), R(70), "Single Egg", "Double Egg")],
    sortOrder: 4,
  },
  {
    id: "rb_chicken_tikka_roll",
    categoryId: "cat_rb_rolls",
    name: "Chicken Roll / Chicken Tikka Roll",
    description: "Juicy chicken wrapped in a golden paratha.",
    isVeg: false,
    pricePaise: R(90),
    isPopular: true,
    addOnGroups: [portionGroup(R(90), R(120), "Chicken Roll", "Chicken Tikka Roll")],
    sortOrder: 5,
  },
  {
    id: "rb_chicken_cheese_roll",
    categoryId: "cat_rb_rolls",
    name: "Chicken Cheese Roll",
    description: "Chicken roll loaded with melted cheese and sauces.",
    isVeg: false,
    pricePaise: R(130),
    isPopular: true,
    sortOrder: 6,
  },

  // ── 11. SALADS & PAPADS ──────────────────────────────────────────────
  {
    id: "rb_green_salad",
    categoryId: "cat_rb_salads",
    name: "Green Salad",
    description: "Fresh sliced cucumber, tomato, carrot and onion salad.",
    isVeg: true,
    pricePaise: R(60),
    sortOrder: 1,
  },
  {
    id: "rb_onion_salad",
    categoryId: "cat_rb_salads",
    name: "Onion Salad",
    description: "Sliced onion rings sprinkled with chaat masala and lemon.",
    isVeg: true,
    pricePaise: R(50),
    sortOrder: 2,
  },
  {
    id: "rb_fruit_salad",
    categoryId: "cat_rb_salads",
    name: "Fruit Salad",
    description: "Assorted fresh seasonal diced fruits.",
    isVeg: true,
    pricePaise: R(100),
    sortOrder: 3,
  },
  {
    id: "rb_dry_papad",
    categoryId: "cat_rb_salads",
    name: "Dry Papad",
    description: "Crispy roasted papad.",
    isVeg: true,
    pricePaise: R(25),
    sortOrder: 4,
  },
  {
    id: "rb_fry_papad",
    categoryId: "cat_rb_salads",
    name: "Fry Papad",
    description: "Deep fried crispy papad.",
    isVeg: true,
    pricePaise: R(25),
    sortOrder: 5,
  },
  {
    id: "rb_masala_papad",
    categoryId: "cat_rb_salads",
    name: "Masala Papad",
    description: "Fried papad topped with spicy onion, tomato and coriander salsa.",
    isVeg: true,
    pricePaise: R(45),
    isPopular: true,
    sortOrder: 6,
  },

  // ── 12. RAITAS ───────────────────────────────────────────────────────
  {
    id: "rb_curd",
    categoryId: "cat_rb_raita",
    name: "Plain Curd",
    description: "Fresh sweetened or plain chilled dahi.",
    isVeg: true,
    pricePaise: R(60),
    sortOrder: 1,
  },
  {
    id: "rb_mix_veg_raita",
    categoryId: "cat_rb_raita",
    name: "Mix Veg. Raita",
    description: "Spiced yogurt with chopped cucumber, tomato and roasted cumin.",
    isVeg: true,
    pricePaise: R(70),
    sortOrder: 2,
  },
  {
    id: "rb_cucumber_raita",
    categoryId: "cat_rb_raita",
    name: "Cucumber Raita",
    description: "Chilled yogurt mixed with grated cucumber and black salt.",
    isVeg: true,
    pricePaise: R(60),
    sortOrder: 3,
  },
  {
    id: "rb_boondi_raita",
    categoryId: "cat_rb_raita",
    name: "Boondi Raita",
    description: "Crisp gram flour boondi in tempered spiced yogurt.",
    isVeg: true,
    pricePaise: R(60),
    isPopular: true,
    sortOrder: 4,
  },
  {
    id: "rb_pineapple_raita",
    categoryId: "cat_rb_raita",
    name: "Pineapple Raita",
    description: "Sweet chilled yogurt with juicy pineapple tidbits.",
    isVeg: true,
    pricePaise: R(90),
    isPopular: true,
    sortOrder: 5,
  },

  // ── 13. BEVERAGES ────────────────────────────────────────────────────
  {
    id: "rb_mineral_water",
    categoryId: "cat_rb_beverages",
    name: "Mineral Water (1L)",
    description: "Packaged sealed drinking water.",
    isVeg: true,
    pricePaise: R(25),
    sortOrder: 1,
  },
  {
    id: "rb_cold_drink",
    categoryId: "cat_rb_beverages",
    name: "Cold Drink",
    description: "Chilled carbonated soft beverage.",
    isVeg: true,
    pricePaise: R(50),
    sortOrder: 2,
  },
  {
    id: "rb_masala_cold_drink",
    categoryId: "cat_rb_beverages",
    name: "Masala Cold Drink",
    description: "Spiced refreshing cola with lemon and masala.",
    isVeg: true,
    pricePaise: R(60),
    sortOrder: 3,
  },
  {
    id: "rb_tea",
    categoryId: "cat_rb_beverages",
    name: "Tea",
    description: "Hot brewed milk tea.",
    isVeg: true,
    pricePaise: R(30),
    sortOrder: 4,
  },
  {
    id: "rb_masala_tea",
    categoryId: "cat_rb_beverages",
    name: "Masala Tea",
    description: "Strong kadak spiced tea.",
    isVeg: true,
    pricePaise: R(40),
    sortOrder: 5,
  },
  {
    id: "rb_coffee",
    categoryId: "cat_rb_beverages",
    name: "Hot Coffee",
    description: "Steaming hot frothy coffee.",
    isVeg: true,
    pricePaise: R(40),
    sortOrder: 6,
  },
  {
    id: "rb_cold_coffee",
    categoryId: "cat_rb_beverages",
    name: "Cold Coffee",
    description: "Chilled thick blended cold coffee.",
    isVeg: true,
    pricePaise: R(90),
    isPopular: true,
    sortOrder: 7,
  },
  {
    id: "rb_milk_shake",
    categoryId: "cat_rb_beverages",
    name: "Milk Shake",
    description: "Delicious blended milk shake.",
    isVeg: true,
    pricePaise: R(90),
    sortOrder: 8,
  },
  {
    id: "rb_fresh_lime_soda",
    categoryId: "cat_rb_beverages",
    name: "Fresh Lime Soda",
    description: "Sweet or salted refreshing lime soda.",
    isVeg: true,
    pricePaise: R(50),
    sortOrder: 9,
  },
  {
    id: "rb_special_lassi",
    categoryId: "cat_rb_beverages",
    name: "Special Lassi",
    description: "Rich traditional sweet thick Punjabi lassi.",
    isVeg: true,
    pricePaise: R(80),
    isPopular: true,
    sortOrder: 10,
  },

  // ── 14. DESSERTS ─────────────────────────────────────────────────────
  {
    id: "rb_gulab_jamun",
    categoryId: "cat_rb_desserts",
    name: "Gulab Jamun (2 Pcs)",
    description: "Warm soft khoya dumplings soaked in sugar syrup.",
    isVeg: true,
    pricePaise: R(40),
    isPopular: true,
    sortOrder: 1,
  },
  {
    id: "rb_rasgulla",
    categoryId: "cat_rb_desserts",
    name: "Rasgulla (2 Pcs)",
    description: "Spongy cottage cheese balls soaked in light syrup.",
    isVeg: true,
    pricePaise: R(50),
    sortOrder: 2,
  },
  {
    id: "rb_ice_cream",
    categoryId: "cat_rb_desserts",
    name: "Ice Cream",
    description: "Chilled scoop of delicious ice cream.",
    isVeg: true,
    pricePaise: R(60),
    sortOrder: 3,
  },
];

/* ══════════════════════════════════════════════════════════════════════
   Main Seed Runner
   ══════════════════════════════════════════════════════════════════════ */

export async function seedRoyalBihar(): Promise<void> {
  console.log("=== Onboarding The Royal Bihar Restaurant ===");

  const campusesCollection = await db.campuses();
  const campus = await campusesCollection.findOne({ _id: CAMPUS_ID });
  if (!campus) {
    throw new Error(`Campus "${CAMPUS_ID}" not found. Run "npm run seed" first.`);
  }

  const now = new Date();
  const servedZoneIds = campus.zones.map((z) => z.id);

  // 1. Upsert Restaurant
  const restaurant: Restaurant = {
    _id: RESTAURANT_ID,
    campusId: CAMPUS_ID,
    slug: "the-royal-bihar-restaurant",
    name: "The Royal Bihar Restaurant",
    cuisines: [
      "North Indian",
      "Bihari",
      "Mughlai",
      "Biryani",
      "Chinese",
      "Tandoor",
      "Rolls",
      "Breads",
    ],
    phone: "9876543211",
    description:
      "The Royal Bihar Restaurant - Authentic Bihari Dehati curries, Handi Mutton, Tandoori Kebabs, Dum Biryanis & North Indian delicacies.",
    imageUrl: null,
    bannerUrl: null,
    packagingFeePaise: R(10),
    minOrderPaise: R(50),
    prepMinutes: 20,
    foodGstBps: 0,
    commissionBpsOverride: null,
    servedZoneIds,
    opensMinutes: 0, // 24x7 service
    closesMinutes: 1439,
    isOpen: true,
    isApproved: true,
    rating: 4.8,
    ratingCount: 56,
    kyc: {
      status: "APPROVED",
      ownerName: "Royal Bihar Manager",
      ownerPhone: "9876543211",
      gstin: null,
      fssai: null,
      reviewedAt: now,
      reviewedBy: "user_admin",
      rejectionReason: null,
    },
    payout: {
      accountName: "The Royal Bihar Restaurant",
      accountNumber: "987654321100",
      ifsc: "SBIN0001234",
      upiId: "royalbihar@upi",
    },
    expiryCountToday: 0,
    autoClosedAt: null,
    createdAt: now,
    updatedAt: now,
  };

  const restaurantsCollection = await db.restaurants();
  await restaurantsCollection.replaceOne({ _id: RESTAURANT_ID }, restaurant, { upsert: true });
  console.log(`[x] Restaurant "${restaurant.name}" created/updated.`);

  // 2. Upsert Vendor Account
  const usersCollection = await db.users();
  const vendorUser: User = {
    _id: VENDOR_USER_ID,
    authId: null,
    role: ROLE.VENDOR_OWNER,
    name: "Royal Bihar Manager",
    email: VENDOR_EMAIL,
    phone: "9876543211",
    passwordHash: hashPassword("royalbihartraefood123"),
    campusId: CAMPUS_ID,
    restaurantId: RESTAURANT_ID,
    codBlocked: false,
    codBlockedReason: null,
    strikes: 0,
    createdAt: now,
    updatedAt: now,
  };

  await usersCollection.replaceOne({ _id: VENDOR_USER_ID }, vendorUser, { upsert: true });
  console.log(`[x] Vendor User "${VENDOR_EMAIL}" created/updated.`);

  // 3. Upsert Categories
  const categoriesCollection = await db.menuCategories();
  await categoriesCollection.deleteMany({ restaurantId: RESTAURANT_ID });

  const categoryDocs: MenuCategory[] = CATEGORIES.map((cat) => ({
    _id: cat.id,
    restaurantId: RESTAURANT_ID,
    name: cat.name,
    sortOrder: cat.sortOrder,
  }));

  await categoriesCollection.insertMany(categoryDocs);
  console.log(`[x] ${categoryDocs.length} menu categories seeded.`);

  // 4. Upsert Menu Items
  const itemsCollection = await db.menuItems();
  await itemsCollection.deleteMany({ restaurantId: RESTAURANT_ID });

  const itemDocs: MenuItem[] = ITEMS.map((item) => ({
    _id: item.id,
    restaurantId: RESTAURANT_ID,
    categoryId: item.categoryId,
    name: item.name,
    description: item.description,
    isVeg: item.isVeg,
    pricePaise: item.pricePaise,
    imageUrl: null,
    isAvailable: true,
    isPopular: item.isPopular ?? false,
    addOnGroups: item.addOnGroups ?? [],
    sortOrder: item.sortOrder,
  }));

  await itemsCollection.insertMany(itemDocs);
  console.log(`[x] ${itemDocs.length} menu items seeded with portion & quantity options.`);

  console.log("\n=== The Royal Bihar Restaurant Ready! ===");
  console.log(`  - Student URL: /c/${campus.slug}/r/${restaurant.slug}`);
  console.log(`  - Admin Menu URL: /admin/vendors/${RESTAURANT_ID}/menu`);
  console.log(`  - Vendor Login: ${VENDOR_EMAIL} / royalbihartraefood123`);
}

async function main() {
  try {
    await seedRoyalBihar();
  } finally {
    const client = await getMongoClient();
    await client.close();
  }
}

if (require.main === module || process.argv[1]?.includes("seed-royal-bihar")) {
  main().catch((err) => {
    console.error("Failed to seed The Royal Bihar Restaurant:", err);
    process.exit(1);
  });
}
