/**
 * Sone Zone Cafe Onboarding & Menu Seeding Script.
 *
 * Seeds:
 * 1. The restaurant profile for Sone Zone Cafe
 * 2. The vendor account login (sonezoneworks@gmail.com / sonezonecafe@1995)
 * 3. All 21 categories and 140+ menu items transcribed from official menu photos.
 *
 * Usage:
 *   node --env-file-if-exists=.env.local --conditions=react-server --import tsx scripts/seed-sone-zone.ts
 */

import { ROLE } from "@/lib/constants";
import { rupeesToPaise, type Paise } from "@/lib/money";
import { hashPassword } from "@/server/auth/passwords";
import { getMongoClient } from "@/server/db/client";
import * as db from "@/server/db/collections";
import type { AddOnGroup, MenuCategory, MenuItem, Restaurant } from "@/types/restaurant";
import type { User } from "@/types/user";
import { CAMPUS_ID } from "./seed-data";

const RESTAURANT_ID = "rest_sone_zone_nitp";
const VENDOR_USER_ID = "usr_sone_zone_vendor";
const VENDOR_EMAIL = "sonezoneworks@gmail.com";

const R = rupeesToPaise;

function sizeGroup(regularPaise: Paise, largePaise: Paise, label1 = "Regular", label2 = "Large"): AddOnGroup {
  return {
    id: "grp_size",
    name: "Size / Quantity",
    minSelect: 1,
    maxSelect: 1,
    options: [
      { id: "opt_size_1", name: label1, pricePaise: 0, isAvailable: true },
      { id: "opt_size_2", name: label2, pricePaise: largePaise - regularPaise, isAvailable: true },
    ],
  };
}

function preparationGroup(dryPaise: Paise, gravyPaise: Paise): AddOnGroup {
  return {
    id: "grp_prep",
    name: "Preparation Style",
    minSelect: 1,
    maxSelect: 1,
    options: [
      { id: "opt_dry", name: "Dry", pricePaise: 0, isAvailable: true },
      { id: "opt_gravy", name: "Gravy", pricePaise: gravyPaise - dryPaise, isAvailable: true },
    ],
  };
}

function butterOptionGroup(plainPaise: Paise, butterPaise: Paise): AddOnGroup {
  return {
    id: "grp_butter",
    name: "Butter Option",
    minSelect: 1,
    maxSelect: 1,
    options: [
      { id: "opt_plain", name: "Plain", pricePaise: 0, isAvailable: true },
      { id: "opt_butter", name: "With Butter", pricePaise: butterPaise - plainPaise, isAvailable: true },
    ],
  };
}

/* ══════════════════════════════════════════════════════════════════════
   Categories
   ══════════════════════════════════════════════════════════════════════ */

const CATEGORIES: { id: string; name: string; sortOrder: number }[] = [
  { id: "cat_sz_tea_coffee", name: "Tea & Coffee", sortOrder: 1 },
  { id: "cat_sz_shakes", name: "Shakes & Lassi", sortOrder: 2 },
  { id: "cat_sz_mocktails", name: "Mocktails & Coolers", sortOrder: 3 },
  { id: "cat_sz_pasta", name: "Pasta", sortOrder: 4 },
  { id: "cat_sz_pizza", name: "Pizza", sortOrder: 5 },
  { id: "cat_sz_burger", name: "Burgers", sortOrder: 6 },
  { id: "cat_sz_maggi", name: "Maggi", sortOrder: 7 },
  { id: "cat_sz_sandwiches", name: "Sandwiches & Snacks", sortOrder: 8 },
  { id: "cat_sz_momos", name: "Momos", sortOrder: 9 },
  { id: "cat_sz_rolls", name: "Rolls", sortOrder: 10 },
  { id: "cat_sz_chinese_starters", name: "Chinese Starters", sortOrder: 11 },
  { id: "cat_sz_chinese_rice", name: "Chinese Fried Rice", sortOrder: 12 },
  { id: "cat_sz_noodles", name: "Noodles", sortOrder: 13 },
  { id: "cat_sz_south_indian", name: "South Indian", sortOrder: 14 },
  { id: "cat_sz_veg_main", name: "Indian Main Course (Veg)", sortOrder: 15 },
  { id: "cat_sz_nonveg_main", name: "Indian Main Course (Non-Veg)", sortOrder: 16 },
  { id: "cat_sz_biryani", name: "Biryani", sortOrder: 17 },
  { id: "cat_sz_dal_rice", name: "Dal & Rice", sortOrder: 18 },
  { id: "cat_sz_thali", name: "Special Thalis", sortOrder: 19 },
  { id: "cat_sz_breads", name: "Indian Breads", sortOrder: 20 },
  { id: "cat_sz_soups", name: "Soups", sortOrder: 21 },
];

/* ══════════════════════════════════════════════════════════════════════
   Menu Items Definition
   ══════════════════════════════════════════════════════════════════════ */

interface ItemDef {
  id: string;
  categoryId: string;
  name: string;
  description: string;
  isVeg: boolean;
  pricePaise: Paise;
  isPopular?: boolean;
  addOnGroups?: AddOnGroup[];
  sortOrder: number;
}

const ITEMS: ItemDef[] = [
  // ── 1. TEA & COFFEE ──────────────────────────────────────────────────
  {
    id: "sz_milk_tea",
    categoryId: "cat_sz_tea_coffee",
    name: "Milk Tea",
    description: "Freshly brewed hot milk tea.",
    isVeg: true,
    pricePaise: R(12),
    sortOrder: 1,
  },
  {
    id: "sz_tandoori_tea",
    categoryId: "cat_sz_tea_coffee",
    name: "Tandoori Tea",
    description: "Smoky kulhad tandoori chai.",
    isVeg: true,
    pricePaise: R(20),
    isPopular: true,
    sortOrder: 2,
  },
  {
    id: "sz_black_coffee",
    categoryId: "cat_sz_tea_coffee",
    name: "Black Coffee",
    description: "Classic unsweetened pure black brew.",
    isVeg: true,
    pricePaise: R(20),
    sortOrder: 3,
  },
  {
    id: "sz_hot_coffee",
    categoryId: "cat_sz_tea_coffee",
    name: "Hot Coffee",
    description: "Steaming frothy hot coffee.",
    isVeg: true,
    pricePaise: R(40),
    sortOrder: 4,
  },
  {
    id: "sz_cold_coffee_without_icecream",
    categoryId: "cat_sz_tea_coffee",
    name: "Cold Coffee Without Ice Cream",
    description: "Chilled blended creamy cold coffee.",
    isVeg: true,
    pricePaise: R(60),
    sortOrder: 5,
  },
  {
    id: "sz_cold_coffee_with_icecream",
    categoryId: "cat_sz_tea_coffee",
    name: "Cold Coffee With Ice Cream",
    description: "Rich cold coffee topped with a scoop of vanilla ice cream.",
    isVeg: true,
    pricePaise: R(70),
    isPopular: true,
    sortOrder: 6,
  },

  // ── 2. SHAKES & LASSI ────────────────────────────────────────────────
  {
    id: "sz_mango_shake",
    categoryId: "cat_sz_shakes",
    name: "Mango Shake",
    description: "Thick sweet Alphonso mango shake.",
    isVeg: true,
    pricePaise: R(59),
    addOnGroups: [sizeGroup(R(59), R(79))],
    sortOrder: 1,
  },
  {
    id: "sz_banana_shake",
    categoryId: "cat_sz_shakes",
    name: "Banana Shake",
    description: "Creamy wholesome fresh banana shake.",
    isVeg: true,
    pricePaise: R(49),
    addOnGroups: [sizeGroup(R(49), R(69))],
    sortOrder: 2,
  },
  {
    id: "sz_strawberry_shake",
    categoryId: "cat_sz_shakes",
    name: "Strawberry Shake",
    description: "Chilled sweet pink strawberry shake.",
    isVeg: true,
    pricePaise: R(59),
    addOnGroups: [sizeGroup(R(59), R(79))],
    sortOrder: 3,
  },
  {
    id: "sz_chocolate_shake",
    categoryId: "cat_sz_shakes",
    name: "Chocolate Shake",
    description: "Rich chocolate syrup blended thick shake.",
    isVeg: true,
    pricePaise: R(59),
    isPopular: true,
    addOnGroups: [sizeGroup(R(59), R(79))],
    sortOrder: 4,
  },
  {
    id: "sz_kitkat_shake",
    categoryId: "cat_sz_shakes",
    name: "KitKat Shake",
    description: "Crunchy KitKat chocolate thick shake.",
    isVeg: true,
    pricePaise: R(59),
    isPopular: true,
    addOnGroups: [sizeGroup(R(59), R(79))],
    sortOrder: 5,
  },
  {
    id: "sz_butterscotch_shake",
    categoryId: "cat_sz_shakes",
    name: "Butterscotch Shake",
    description: "Sweet shake loaded with butterscotch praline.",
    isVeg: true,
    pricePaise: R(59),
    addOnGroups: [sizeGroup(R(59), R(79))],
    sortOrder: 6,
  },
  {
    id: "sz_vanilla_shake",
    categoryId: "cat_sz_shakes",
    name: "Vanilla Shake",
    description: "Smooth and creamy pure vanilla shake.",
    isVeg: true,
    pricePaise: R(59),
    addOnGroups: [sizeGroup(R(59), R(79))],
    sortOrder: 7,
  },
  {
    id: "sz_pineapple_shake",
    categoryId: "cat_sz_shakes",
    name: "Pineapple Shake",
    description: "Tropical tangy sweet pineapple shake.",
    isVeg: true,
    pricePaise: R(59),
    addOnGroups: [sizeGroup(R(59), R(79))],
    sortOrder: 8,
  },
  {
    id: "sz_oreo_shake",
    categoryId: "cat_sz_shakes",
    name: "Oreo Shake",
    description: "Crushed Oreo cookies blended in vanilla ice cream.",
    isVeg: true,
    pricePaise: R(69),
    isPopular: true,
    addOnGroups: [sizeGroup(R(69), R(89))],
    sortOrder: 9,
  },
  {
    id: "sz_meethi_lassi",
    categoryId: "cat_sz_shakes",
    name: "Meethi Lassi",
    description: "Traditional sweet thick Punjabi curd lassi.",
    isVeg: true,
    pricePaise: R(50),
    isPopular: true,
    sortOrder: 10,
  },
  {
    id: "sz_namkeen_lassi",
    categoryId: "cat_sz_shakes",
    name: "Namkeen Lassi",
    description: "Salted spiced buttermilk chaas with roasted jeera.",
    isVeg: true,
    pricePaise: R(40),
    sortOrder: 11,
  },

  // ── 3. MOCKTAILS & COOLERS ───────────────────────────────────────────
  {
    id: "sz_virgin_mojito",
    categoryId: "cat_sz_mocktails",
    name: "Virgin Mojito",
    description: "Mint, fresh lime and fizzy soda over crushed ice.",
    isVeg: true,
    pricePaise: R(90),
    isPopular: true,
    sortOrder: 1,
  },
  {
    id: "sz_blue_ocean",
    categoryId: "cat_sz_mocktails",
    name: "Blue Ocean",
    description: "Vibrant blue Curacao mocktail with lemon zest.",
    isVeg: true,
    pricePaise: R(100),
    sortOrder: 2,
  },
  {
    id: "sz_mint_mojito",
    categoryId: "cat_sz_mocktails",
    name: "Mint Mojito",
    description: "Extra refreshing garden mint cooler.",
    isVeg: true,
    pricePaise: R(95),
    sortOrder: 3,
  },
  {
    id: "sz_mango_mojito",
    categoryId: "cat_sz_mocktails",
    name: "Mango Mojito",
    description: "Sweet mango pulp with mint and soda.",
    isVeg: true,
    pricePaise: R(95),
    sortOrder: 4,
  },
  {
    id: "sz_orange_mojito",
    categoryId: "cat_sz_mocktails",
    name: "Orange Mojito",
    description: "Citrus orange cooler with mint sprigs.",
    isVeg: true,
    pricePaise: R(95),
    sortOrder: 5,
  },
  {
    id: "sz_fresh_lime_soda",
    categoryId: "cat_sz_mocktails",
    name: "Fresh Lime Soda",
    description: "Sweet or salted refreshing bubbly lime soda.",
    isVeg: true,
    pricePaise: R(80),
    sortOrder: 6,
  },
  {
    id: "sz_masala_cold_drink",
    categoryId: "cat_sz_mocktails",
    name: "Masala Cold Drink",
    description: "Spiced soda with chaat masala and lemon.",
    isVeg: true,
    pricePaise: R(70),
    sortOrder: 7,
  },
  {
    id: "sz_sunrise_mocktail",
    categoryId: "cat_sz_mocktails",
    name: "Sone Zone Sunrise Mocktail",
    description: "Layered signature fruit punch mocktail.",
    isVeg: true,
    pricePaise: R(150),
    isPopular: true,
    sortOrder: 8,
  },

  // ── 4. PASTA ─────────────────────────────────────────────────────────
  {
    id: "sz_red_sauce_pasta",
    categoryId: "cat_sz_pasta",
    name: "Red Sauce Pasta",
    description: "Penne tossed in spicy Italian tomato sauce.",
    isVeg: true,
    pricePaise: R(99),
    sortOrder: 1,
  },
  {
    id: "sz_white_sauce_pasta",
    categoryId: "cat_sz_pasta",
    name: "White Sauce Pasta",
    description: "Creamy Alfredo white sauce penne pasta.",
    isVeg: true,
    pricePaise: R(109),
    isPopular: true,
    sortOrder: 2,
  },
  {
    id: "sz_chinese_pasta",
    categoryId: "cat_sz_pasta",
    name: "Chinese Pasta",
    description: "Desi fusion spicy wok-tossed pasta with veggies.",
    isVeg: true,
    pricePaise: R(109),
    sortOrder: 3,
  },
  {
    id: "sz_special_pasta",
    categoryId: "cat_sz_pasta",
    name: "Sone Zone Special Pasta",
    description: "Signature pink mixed sauce pasta with loaded cheese.",
    isVeg: true,
    pricePaise: R(119),
    isPopular: true,
    sortOrder: 4,
  },

  // ── 5. PIZZA ─────────────────────────────────────────────────────────
  {
    id: "sz_margherita_pizza",
    categoryId: "cat_sz_pizza",
    name: "Margherita Pizza",
    description: "Classic pizza with tomato sauce and mozzarella cheese.",
    isVeg: true,
    pricePaise: R(119),
    sortOrder: 1,
  },
  {
    id: "sz_onion_pizza",
    categoryId: "cat_sz_pizza",
    name: "Onion Pizza",
    description: "Crispy sliced onions and melted cheese.",
    isVeg: true,
    pricePaise: R(129),
    sortOrder: 2,
  },
  {
    id: "sz_sweet_corn_pizza",
    categoryId: "cat_sz_pizza",
    name: "Sweet Corn Pizza",
    description: "Sweet golden corn with melted mozzarella.",
    isVeg: true,
    pricePaise: R(149),
    sortOrder: 3,
  },
  {
    id: "sz_mushroom_tikka_pizza",
    categoryId: "cat_sz_pizza",
    name: "Mushroom Tikka Pizza",
    description: "Spiced mushroom chunks, onions and cheese.",
    isVeg: true,
    pricePaise: R(169),
    sortOrder: 4,
  },
  {
    id: "sz_paneer_tikka_pizza",
    categoryId: "cat_sz_pizza",
    name: "Paneer Tikka Pizza",
    description: "Tandoori paneer cubes, capsicum and cheese.",
    isVeg: true,
    pricePaise: R(169),
    isPopular: true,
    sortOrder: 5,
  },
  {
    id: "sz_chicken_tikka_pizza",
    categoryId: "cat_sz_pizza",
    name: "Chicken Tikka Pizza",
    description: "Tandoori roasted chicken tikkas and melted cheese.",
    isVeg: false,
    pricePaise: R(199),
    isPopular: true,
    sortOrder: 6,
  },
  {
    id: "sz_sone_zone_veg_pizza",
    categoryId: "cat_sz_pizza",
    name: "Sone Zone Veg Pizza",
    description: "Loaded with paneer, corn, capsicum, mushroom & olives.",
    isVeg: true,
    pricePaise: R(209),
    isPopular: true,
    sortOrder: 7,
  },
  {
    id: "sz_non_veg_pizza",
    categoryId: "cat_sz_pizza",
    name: "Non-Veg Pizza",
    description: "Special loaded chicken supreme pizza.",
    isVeg: false,
    pricePaise: R(249),
    isPopular: true,
    sortOrder: 8,
  },

  // ── 6. BURGERS ───────────────────────────────────────────────────────
  {
    id: "sz_veg_burger",
    categoryId: "cat_sz_burger",
    name: "Veg Burger",
    description: "Crispy potato-veggie patty with mayo.",
    isVeg: true,
    pricePaise: R(59),
    sortOrder: 1,
  },
  {
    id: "sz_noodle_burger",
    categoryId: "cat_sz_burger",
    name: "Noodle Burger",
    description: "Desi style burger stuffed with spicy chowmein noodles.",
    isVeg: true,
    pricePaise: R(69),
    isPopular: true,
    sortOrder: 2,
  },
  {
    id: "sz_cheese_burger",
    categoryId: "cat_sz_burger",
    name: "Cheese Burger",
    description: "Crispy patty topped with melted cheese slice.",
    isVeg: true,
    pricePaise: R(79),
    sortOrder: 3,
  },
  {
    id: "sz_noodle_cream_burger",
    categoryId: "cat_sz_burger",
    name: "Noodle Cream Burger",
    description: "Stuffed with creamy mayonnaise chowmein noodles.",
    isVeg: true,
    pricePaise: R(89),
    sortOrder: 4,
  },
  {
    id: "sz_paneer_burger",
    categoryId: "cat_sz_burger",
    name: "Paneer Burger",
    description: "Grilled cottage cheese patty with secret spices.",
    isVeg: true,
    pricePaise: R(79),
    sortOrder: 5,
  },
  {
    id: "sz_special_burger",
    categoryId: "cat_sz_burger",
    name: "Sone Zone Special Burger",
    description: "Double patty giant burger with loaded cheese & sauces.",
    isVeg: true,
    pricePaise: R(109),
    isPopular: true,
    sortOrder: 6,
  },

  // ── 7. MAGGI ─────────────────────────────────────────────────────────
  {
    id: "sz_plain_maggi",
    categoryId: "cat_sz_maggi",
    name: "Plain Maggi",
    description: "Classic instant 2-minute masala Maggi.",
    isVeg: true,
    pricePaise: R(59),
    sortOrder: 1,
  },
  {
    id: "sz_masala_maggi",
    categoryId: "cat_sz_maggi",
    name: "Masala Maggi",
    description: "Extra spicy Maggi with roasted masala seasonings.",
    isVeg: true,
    pricePaise: R(69),
    sortOrder: 2,
  },
  {
    id: "sz_veggie_maggi",
    categoryId: "cat_sz_maggi",
    name: "Veggie Maggi",
    description: "Tossed with onions, tomatoes, peas and carrots.",
    isVeg: true,
    pricePaise: R(79),
    sortOrder: 3,
  },
  {
    id: "sz_cheese_maggi",
    categoryId: "cat_sz_maggi",
    name: "Cheese Maggi",
    description: "Loaded with melted mozzarella cheese.",
    isVeg: true,
    pricePaise: R(79),
    isPopular: true,
    sortOrder: 4,
  },
  {
    id: "sz_paneer_maggi",
    categoryId: "cat_sz_maggi",
    name: "Paneer Maggi",
    description: "Simmered with fresh diced cottage cheese cubes.",
    isVeg: true,
    pricePaise: R(89),
    sortOrder: 5,
  },
  {
    id: "sz_special_maggi",
    categoryId: "cat_sz_maggi",
    name: "Sone Zone Special Maggi",
    description: "Loaded bowl with paneer, cheese, corn and veggies.",
    isVeg: true,
    pricePaise: R(99),
    isPopular: true,
    sortOrder: 6,
  },

  // ── 8. SANDWICHES & SNACKS ───────────────────────────────────────────
  {
    id: "sz_grilled_sandwich",
    categoryId: "cat_sz_sandwiches",
    name: "Grilled Sandwich",
    description: "Crispy grilled vegetable sandwich.",
    isVeg: true,
    pricePaise: R(79),
    sortOrder: 1,
  },
  {
    id: "sz_veg_sandwich",
    categoryId: "cat_sz_sandwiches",
    name: "Veg Sandwich",
    description: "Fresh vegetable cold sandwich.",
    isVeg: true,
    pricePaise: R(89),
    sortOrder: 2,
  },
  {
    id: "sz_paneer_grilled_sandwich",
    categoryId: "cat_sz_sandwiches",
    name: "Paneer Grilled Sandwich",
    description: "Spiced paneer filling grilled to golden crispness.",
    isVeg: true,
    pricePaise: R(99),
    isPopular: true,
    sortOrder: 3,
  },
  {
    id: "sz_garlic_bread",
    categoryId: "cat_sz_sandwiches",
    name: "Garlic Bread",
    description: "Toasted bread brushed with garlic herb butter.",
    isVeg: true,
    pricePaise: R(99),
    sortOrder: 4,
  },
  {
    id: "sz_butter_toast",
    categoryId: "cat_sz_sandwiches",
    name: "Butter Toast",
    description: "Crisp toasted bread with salted butter.",
    isVeg: true,
    pricePaise: R(120),
    sortOrder: 5,
  },
  {
    id: "sz_jam_toast",
    categoryId: "cat_sz_sandwiches",
    name: "Jam Toast",
    description: "Toasted bread with fruit jam.",
    isVeg: true,
    pricePaise: R(120),
    sortOrder: 6,
  },
  {
    id: "sz_chocolate_spread_toast",
    categoryId: "cat_sz_sandwiches",
    name: "Chocolate Spread Toast",
    description: "Warm toast generously smeared with hazelnut chocolate.",
    isVeg: true,
    pricePaise: R(139),
    sortOrder: 7,
  },
  {
    id: "sz_french_fries",
    categoryId: "cat_sz_sandwiches",
    name: "French Fries",
    description: "Crispy salted golden potato fries.",
    isVeg: true,
    pricePaise: R(89),
    sortOrder: 8,
  },
  {
    id: "sz_peri_peri_fries",
    categoryId: "cat_sz_sandwiches",
    name: "Peri-Peri Fries",
    description: "Fries tossed in spicy African peri-peri dust.",
    isVeg: true,
    pricePaise: R(89),
    isPopular: true,
    sortOrder: 9,
  },
  {
    id: "sz_bread_pakoda_8pc",
    categoryId: "cat_sz_sandwiches",
    name: "Bread Pakoda (8 Pc)",
    description: "Spiced potato stuffed crispy bread pakoras.",
    isVeg: true,
    pricePaise: R(89),
    sortOrder: 10,
  },
  {
    id: "sz_onion_pakoda_8pc",
    categoryId: "cat_sz_sandwiches",
    name: "Onion Pakoda (8 Pc)",
    description: "Crisp golden onion fritters with chaat masala.",
    isVeg: true,
    pricePaise: R(79),
    sortOrder: 11,
  },
  {
    id: "sz_veg_pakoda_8pc",
    categoryId: "cat_sz_sandwiches",
    name: "Veg Pakoda (8 Pc)",
    description: "Assorted crispy vegetable fritters.",
    isVeg: true,
    pricePaise: R(89),
    sortOrder: 12,
  },
  {
    id: "sz_paneer_pakoda_8pc",
    categoryId: "cat_sz_sandwiches",
    name: "Paneer Pakoda (8 Pc)",
    description: "Golden fried batter-coated paneer pakodas.",
    isVeg: true,
    pricePaise: R(109),
    isPopular: true,
    sortOrder: 13,
  },

  // ── 9. MOMOS ─────────────────────────────────────────────────────────
  {
    id: "sz_steam_veg_momos",
    categoryId: "cat_sz_momos",
    name: "Steam Veg Momos (8 Pc)",
    description: "Steamed vegetable dumplings with spicy red dip.",
    isVeg: true,
    pricePaise: R(69),
    sortOrder: 1,
  },
  {
    id: "sz_fry_veg_momos",
    categoryId: "cat_sz_momos",
    name: "Fry Veg Momos (8 Pc)",
    description: "Crispy fried vegetable momos.",
    isVeg: true,
    pricePaise: R(79),
    sortOrder: 2,
  },
  {
    id: "sz_steam_paneer_momos",
    categoryId: "cat_sz_momos",
    name: "Steam Paneer Momos (8 Pc)",
    description: "Steamed momos stuffed with spiced cottage cheese.",
    isVeg: true,
    pricePaise: R(89),
    sortOrder: 3,
  },
  {
    id: "sz_fry_paneer_momos",
    categoryId: "cat_sz_momos",
    name: "Fry Paneer Momos (8 Pc)",
    description: "Golden fried crunchy paneer momos.",
    isVeg: true,
    pricePaise: R(99),
    sortOrder: 4,
  },
  {
    id: "sz_crispy_veg_momos",
    categoryId: "cat_sz_momos",
    name: "Crispy Veg Momos (8 Pc)",
    description: "Kurkure coated crunchy fried momos.",
    isVeg: true,
    pricePaise: R(109),
    isPopular: true,
    sortOrder: 5,
  },

  // ── 10. ROLLS ────────────────────────────────────────────────────────
  {
    id: "sz_veg_roll",
    categoryId: "cat_sz_rolls",
    name: "Veg Roll",
    description: "Spiced vegetable filling in a flaky paratha roll.",
    isVeg: true,
    pricePaise: R(59),
    sortOrder: 1,
  },
  {
    id: "sz_paneer_roll",
    categoryId: "cat_sz_rolls",
    name: "Paneer Roll",
    description: "Tossed paneer cubes with onions and tangy mint chutney.",
    isVeg: true,
    pricePaise: R(79),
    isPopular: true,
    sortOrder: 2,
  },
  {
    id: "sz_egg_roll",
    categoryId: "cat_sz_rolls",
    name: "Egg Roll",
    description: "Egg layered paratha roll with sliced onion salad.",
    isVeg: false,
    pricePaise: R(69),
    sortOrder: 3,
  },
  {
    id: "sz_chicken_roll",
    categoryId: "cat_sz_rolls",
    name: "Chicken Roll",
    description: "Juicy marinated chicken pieces rolled in hot paratha.",
    isVeg: false,
    pricePaise: R(99),
    isPopular: true,
    sortOrder: 4,
  },
  {
    id: "sz_spring_roll",
    categoryId: "cat_sz_rolls",
    name: "Spring Roll",
    description: "Crispy Chinese vegetable spring rolls.",
    isVeg: true,
    pricePaise: R(89),
    sortOrder: 5,
  },
  {
    id: "sz_special_veg_roll",
    categoryId: "cat_sz_rolls",
    name: "Sone Zone Special Veg Roll",
    description: "Loaded paneer, cheese and spiced veggies roll.",
    isVeg: true,
    pricePaise: R(119),
    isPopular: true,
    sortOrder: 6,
  },
  {
    id: "sz_special_nonveg_roll",
    categoryId: "cat_sz_rolls",
    name: "Sone Zone Non-Veg Roll",
    description: "Double chicken and egg loaded special roll.",
    isVeg: false,
    pricePaise: R(129),
    isPopular: true,
    sortOrder: 7,
  },

  // ── 11. CHINESE STARTERS ─────────────────────────────────────────────
  {
    id: "sz_veg_manchurian",
    categoryId: "cat_sz_chinese_starters",
    name: "Veg Manchurian",
    description: "Crisp vegetable balls in garlic soya sauce.",
    isVeg: true,
    pricePaise: R(79),
    addOnGroups: [preparationGroup(R(79), R(89))],
    sortOrder: 1,
  },
  {
    id: "sz_paneer_manchurian",
    categoryId: "cat_sz_chinese_starters",
    name: "Paneer Manchurian",
    description: "Cottage cheese cubes tossed in spicy Manchurian sauce.",
    isVeg: true,
    pricePaise: R(119),
    addOnGroups: [preparationGroup(R(119), R(129))],
    sortOrder: 2,
  },
  {
    id: "sz_chicken_manchurian",
    categoryId: "cat_sz_chinese_starters",
    name: "Chicken Manchurian",
    description: "Chicken meatballs in rich Indo-Chinese gravy or dry.",
    isVeg: false,
    pricePaise: R(129),
    addOnGroups: [preparationGroup(R(129), R(139))],
    sortOrder: 3,
  },
  {
    id: "sz_honey_chilli_potato",
    categoryId: "cat_sz_chinese_starters",
    name: "Honey Chilli Potato",
    description: "Sweet and spicy crispy potato fingers.",
    isVeg: true,
    pricePaise: R(119),
    isPopular: true,
    sortOrder: 4,
  },
  {
    id: "sz_babycorn_chilli",
    categoryId: "cat_sz_chinese_starters",
    name: "Babycorn Chilli",
    description: "Crispy baby corn tossed with capsicum and chillies.",
    isVeg: true,
    pricePaise: R(149),
    addOnGroups: [preparationGroup(R(149), R(159))],
    sortOrder: 5,
  },
  {
    id: "sz_paneer_chilli",
    categoryId: "cat_sz_chinese_starters",
    name: "Paneer Chilli",
    description: "Fried cottage cheese in spicy chilli soya glaze.",
    isVeg: true,
    pricePaise: R(149),
    isPopular: true,
    addOnGroups: [preparationGroup(R(149), R(159))],
    sortOrder: 6,
  },
  {
    id: "sz_mushroom_chilli",
    categoryId: "cat_sz_chinese_starters",
    name: "Mushroom Chilli",
    description: "Button mushrooms in hot chilli garlic sauce.",
    isVeg: true,
    pricePaise: R(149),
    addOnGroups: [preparationGroup(R(149), R(159))],
    sortOrder: 7,
  },
  {
    id: "sz_chicken_chilli_boneless",
    categoryId: "cat_sz_chinese_starters",
    name: "Chicken Chilli Boneless (8 Pc)",
    description: "Boneless chicken morsels tossed in spicy chilli sauce.",
    isVeg: false,
    pricePaise: R(169),
    isPopular: true,
    sortOrder: 8,
  },
  {
    id: "sz_chicken_chilli_bone",
    categoryId: "cat_sz_chinese_starters",
    name: "Chicken Chilli with Bone (8 Pc)",
    description: "Bone-in chicken tossed in spicy chilli garlic sauce.",
    isVeg: false,
    pricePaise: R(159),
    sortOrder: 9,
  },
  {
    id: "sz_chicken_65",
    categoryId: "cat_sz_chinese_starters",
    name: "Chicken 65 (6 Pc)",
    description: "Crispy spicy South-Indian style deep fried chicken.",
    isVeg: false,
    pricePaise: R(169),
    sortOrder: 10,
  },
  {
    id: "sz_chicken_fry_lollipop",
    categoryId: "cat_sz_chinese_starters",
    name: "Chicken Fry Lollipop (6 Pc)",
    description: "Deep-fried frenched chicken drumettes with hot dip.",
    isVeg: false,
    pricePaise: R(239),
    isPopular: true,
    sortOrder: 11,
  },
  {
    id: "sz_crispy_chicken",
    categoryId: "cat_sz_chinese_starters",
    name: "Crispy Chicken (8 Pc)",
    description: "Golden fried crunchy seasoned chicken bites.",
    isVeg: false,
    pricePaise: R(149),
    sortOrder: 12,
  },
  {
    id: "sz_dragon_chicken",
    categoryId: "cat_sz_chinese_starters",
    name: "Dragon Chicken (8 Pc)",
    description: "Spicy sweet cashewnut glazed chicken strips.",
    isVeg: false,
    pricePaise: R(169),
    isPopular: true,
    sortOrder: 13,
  },
  {
    id: "sz_garlic_chicken",
    categoryId: "cat_sz_chinese_starters",
    name: "Garlic Chicken (8 Pc)",
    description: "Chicken tossed in aromatic burnt garlic sauce.",
    isVeg: false,
    pricePaise: R(169),
    sortOrder: 14,
  },

  // ── 12. CHINESE FRIED RICE ───────────────────────────────────────────
  {
    id: "sz_steam_rice",
    categoryId: "cat_sz_chinese_rice",
    name: "Steam Rice",
    description: "Fluffy steamed long grain rice.",
    isVeg: true,
    pricePaise: R(59),
    sortOrder: 1,
  },
  {
    id: "sz_veg_fried_rice",
    categoryId: "cat_sz_chinese_rice",
    name: "Veg Fried Rice",
    description: "Wok-tossed rice with carrots, beans and spring onions.",
    isVeg: true,
    pricePaise: R(79),
    sortOrder: 2,
  },
  {
    id: "sz_triple_veg_fried_rice",
    categoryId: "cat_sz_chinese_rice",
    name: "Triple Veg Fried Rice",
    description: "Fried rice, noodles and crispy veg Manchurian combo.",
    isVeg: true,
    pricePaise: R(119),
    isPopular: true,
    sortOrder: 3,
  },
  {
    id: "sz_mushroom_tomato_fried_rice",
    categoryId: "cat_sz_chinese_rice",
    name: "Mushroom Tomato Fried Rice",
    description: "Fried rice with mushrooms and ripe tomatoes.",
    isVeg: true,
    pricePaise: R(109),
    sortOrder: 4,
  },
  {
    id: "sz_egg_fried_rice",
    categoryId: "cat_sz_chinese_rice",
    name: "Egg Fried Rice",
    description: "Fried rice scrambled with eggs and pepper.",
    isVeg: false,
    pricePaise: R(99),
    sortOrder: 5,
  },
  {
    id: "sz_chicken_fried_rice",
    categoryId: "cat_sz_chinese_rice",
    name: "Chicken Fried Rice",
    description: "Wok tossed rice loaded with chicken pieces.",
    isVeg: false,
    pricePaise: R(159),
    isPopular: true,
    sortOrder: 6,
  },
  {
    id: "sz_triple_nonveg_fried_rice",
    categoryId: "cat_sz_chinese_rice",
    name: "Triple Non-Veg Fried Rice",
    description: "Chicken fried rice, chicken noodles and chicken gravy.",
    isVeg: false,
    pricePaise: R(199),
    isPopular: true,
    sortOrder: 7,
  },
  {
    id: "sz_schezwan_rice",
    categoryId: "cat_sz_chinese_rice",
    name: "Schezwan Fried Rice",
    description: "Spicy red Schezwan pepper tossed fried rice.",
    isVeg: true,
    pricePaise: R(109),
    addOnGroups: [sizeGroup(R(109), R(179), "Veg (₹109)", "Non-Veg (₹179)")],
    sortOrder: 8,
  },

  // ── 13. NOODLES ──────────────────────────────────────────────────────
  {
    id: "sz_veg_noodles",
    categoryId: "cat_sz_noodles",
    name: "Veg Noodles",
    description: "Simple stir-fried vegetable noodles.",
    isVeg: true,
    pricePaise: R(69),
    sortOrder: 1,
  },
  {
    id: "sz_veg_hakka_noodles",
    categoryId: "cat_sz_noodles",
    name: "Veg Hakka Noodles",
    description: "Classic Indo-Chinese style Hakka noodles.",
    isVeg: true,
    pricePaise: R(119),
    isPopular: true,
    sortOrder: 2,
  },
  {
    id: "sz_veg_gravy_noodles",
    categoryId: "cat_sz_noodles",
    name: "Veg Gravy Noodles",
    description: "Pan-fried noodles served with hot vegetable gravy.",
    isVeg: true,
    pricePaise: R(119),
    sortOrder: 3,
  },
  {
    id: "sz_paneer_noodles",
    categoryId: "cat_sz_noodles",
    name: "Paneer Noodles",
    description: "Stir-fried noodles with soft cottage cheese cubes.",
    isVeg: true,
    pricePaise: R(99),
    sortOrder: 4,
  },
  {
    id: "sz_manchurian_noodles",
    categoryId: "cat_sz_noodles",
    name: "Manchurian Noodles",
    description: "Noodles tossed in spicy vegetable Manchurian sauce.",
    isVeg: true,
    pricePaise: R(99),
    sortOrder: 5,
  },
  {
    id: "sz_chilly_garlic_noodles",
    categoryId: "cat_sz_noodles",
    name: "Chilly Garlic Noodles",
    description: "Fiery spicy noodles with roasted burnt garlic.",
    isVeg: true,
    pricePaise: R(99),
    sortOrder: 6,
  },
  {
    id: "sz_singapore_veg_noodles",
    categoryId: "cat_sz_noodles",
    name: "Singapore Veg Noodles",
    description: "Curry spiced noodles with crunchy vegetables.",
    isVeg: true,
    pricePaise: R(99),
    sortOrder: 7,
  },
  {
    id: "sz_singapore_nonveg_noodles",
    categoryId: "cat_sz_noodles",
    name: "Singapore Non-Veg Noodles",
    description: "Curry spiced noodles with chicken and egg.",
    isVeg: false,
    pricePaise: R(119),
    sortOrder: 8,
  },
  {
    id: "sz_egg_noodles",
    categoryId: "cat_sz_noodles",
    name: "Egg Noodles",
    description: "Wok-tossed noodles with scrambled eggs.",
    isVeg: false,
    pricePaise: R(99),
    sortOrder: 9,
  },
  {
    id: "sz_chicken_hakka_noodles",
    categoryId: "cat_sz_noodles",
    name: "Chicken Hakka Noodles",
    description: "Hakka noodles loaded with chicken shreds.",
    isVeg: false,
    pricePaise: R(129),
    isPopular: true,
    sortOrder: 10,
  },
  {
    id: "sz_special_veg_noodles",
    categoryId: "cat_sz_noodles",
    name: "Sone Zone Special Veg Noodles",
    description: "Loaded noodles with paneer, mushrooms and baby corn.",
    isVeg: true,
    pricePaise: R(139),
    isPopular: true,
    sortOrder: 11,
  },
  {
    id: "sz_special_nonveg_noodles",
    categoryId: "cat_sz_noodles",
    name: "Sone Zone Non-Veg Noodles",
    description: "Special loaded chicken and egg noodles.",
    isVeg: false,
    pricePaise: R(159),
    isPopular: true,
    sortOrder: 12,
  },

  // ── 14. SOUTH INDIAN ─────────────────────────────────────────────────
  {
    id: "sz_plain_dosa",
    categoryId: "cat_sz_south_indian",
    name: "Plain Dosa",
    description: "Crisp golden crepe served with sambhar and coconut chutney.",
    isVeg: true,
    pricePaise: R(89),
    sortOrder: 1,
  },
  {
    id: "sz_onion_dosa",
    categoryId: "cat_sz_south_indian",
    name: "Onion Dosa",
    description: "Crispy dosa sprinkled with chopped onions.",
    isVeg: true,
    pricePaise: R(89),
    sortOrder: 2,
  },
  {
    id: "sz_masala_dosa",
    categoryId: "cat_sz_south_indian",
    name: "Masala Dosa",
    description: "Crispy dosa stuffed with seasoned potato masala.",
    isVeg: true,
    pricePaise: R(99),
    isPopular: true,
    sortOrder: 3,
  },
  {
    id: "sz_paneer_dosa",
    categoryId: "cat_sz_south_indian",
    name: "Paneer Dosa",
    description: "Dosa stuffed with spiced grated cottage cheese.",
    isVeg: true,
    pricePaise: R(109),
    sortOrder: 4,
  },
  {
    id: "sz_special_dosa",
    categoryId: "cat_sz_south_indian",
    name: "Sone Zone Special Dosa",
    description: "Chef's special loaded Mysore masala paneer dosa.",
    isVeg: true,
    pricePaise: R(119),
    isPopular: true,
    sortOrder: 5,
  },
  {
    id: "sz_idli_sambhar",
    categoryId: "cat_sz_south_indian",
    name: "Idli Sambhar",
    description: "Steamed fluffy rice cakes served with hot sambhar.",
    isVeg: true,
    pricePaise: R(59),
    sortOrder: 6,
  },

  // ── 15. INDIAN MAIN COURSE (VEG) ─────────────────────────────────────
  {
    id: "sz_chana_masala",
    categoryId: "cat_sz_veg_main",
    name: "Chana Masala",
    description: "Punjabi style spiced chickpea curry.",
    isVeg: true,
    pricePaise: R(129),
    sortOrder: 1,
  },
  {
    id: "sz_mix_veg",
    categoryId: "cat_sz_veg_main",
    name: "Mix Veg",
    description: "Assorted seasonal garden vegetables in spiced gravy.",
    isVeg: true,
    pricePaise: R(129),
    sortOrder: 2,
  },
  {
    id: "sz_kadhai_mushroom",
    categoryId: "cat_sz_veg_main",
    name: "Kadhai Mushroom",
    description: "Mushrooms wok-cooked with capsicum and kadai spices.",
    isVeg: true,
    pricePaise: R(179),
    sortOrder: 3,
  },
  {
    id: "sz_mushroom_matar",
    categoryId: "cat_sz_veg_main",
    name: "Mushroom Matar",
    description: "Green peas and mushrooms simmered in curry.",
    isVeg: true,
    pricePaise: R(179),
    sortOrder: 4,
  },
  {
    id: "sz_mushroom_do_pyaza",
    categoryId: "cat_sz_veg_main",
    name: "Mushroom Do-Pyaza",
    description: "Mushroom curry cooked with pearl onions.",
    isVeg: true,
    pricePaise: R(179),
    sortOrder: 5,
  },
  {
    id: "sz_paneer_bhurji",
    categoryId: "cat_sz_veg_main",
    name: "Paneer Bhurji",
    description: "Scrambled spiced cottage cheese with onions and tomatoes.",
    isVeg: true,
    pricePaise: R(119),
    isPopular: true,
    sortOrder: 6,
  },
  {
    id: "sz_matar_paneer",
    categoryId: "cat_sz_veg_main",
    name: "Matar Paneer",
    description: "Classic cottage cheese and green peas in spiced gravy.",
    isVeg: true,
    pricePaise: R(189),
    sortOrder: 7,
  },
  {
    id: "sz_kadhai_paneer",
    categoryId: "cat_sz_veg_main",
    name: "Kadhai Paneer",
    description: "Paneer cooked in rich kadai masala and bell peppers.",
    isVeg: true,
    pricePaise: R(199),
    isPopular: true,
    sortOrder: 8,
  },
  {
    id: "sz_handi_paneer",
    categoryId: "cat_sz_veg_main",
    name: "Handi Paneer",
    description: "Slow-cooked earthen pot paneer in rich gravy.",
    isVeg: true,
    pricePaise: R(199),
    sortOrder: 9,
  },
  {
    id: "sz_butter_paneer_masala",
    categoryId: "cat_sz_veg_main",
    name: "Butter Paneer Masala",
    description: "Creamy butter makhani gravy with paneer cubes.",
    isVeg: true,
    pricePaise: R(219),
    isPopular: true,
    sortOrder: 10,
  },
  {
    id: "sz_shahi_paneer",
    categoryId: "cat_sz_veg_main",
    name: "Shahi Paneer",
    description: "Royal cottage cheese curry in sweet cashew gravy.",
    isVeg: true,
    pricePaise: R(219),
    sortOrder: 11,
  },
  {
    id: "sz_palak_paneer",
    categoryId: "cat_sz_veg_main",
    name: "Palak Paneer",
    description: "Paneer cubes in pureed garlicky spinach.",
    isVeg: true,
    pricePaise: R(209),
    sortOrder: 12,
  },
  {
    id: "sz_jeera_aloo",
    categoryId: "cat_sz_veg_main",
    name: "Jeera Aloo",
    description: "Diced potatoes tempered with roasted cumin.",
    isVeg: true,
    pricePaise: R(99),
    sortOrder: 13,
  },
  {
    id: "sz_bhujya_veg",
    categoryId: "cat_sz_veg_main",
    name: "Bihari Bhujiya (Aloo / Gobhi / Bhindi)",
    description: "Traditional Bihari dry pan-fried vegetable bhujiya.",
    isVeg: true,
    pricePaise: R(99),
    isPopular: true,
    sortOrder: 14,
  },

  // ── 16. INDIAN MAIN COURSE (NON-VEG) ─────────────────────────────────
  {
    id: "sz_chicken_curry",
    categoryId: "cat_sz_nonveg_main",
    name: "Chicken Curry",
    description: "Homestyle aromatic chicken curry.",
    isVeg: false,
    pricePaise: R(239),
    isPopular: true,
    sortOrder: 1,
  },
  {
    id: "sz_chicken_masala",
    categoryId: "cat_sz_nonveg_main",
    name: "Chicken Masala",
    description: "Thick spicy onion-tomato chicken masala.",
    isVeg: false,
    pricePaise: R(239),
    sortOrder: 2,
  },
  {
    id: "sz_chicken_handi",
    categoryId: "cat_sz_nonveg_main",
    name: "Chicken Handi",
    description: "Slow-cooked handi chicken in fragrant spices.",
    isVeg: false,
    pricePaise: R(239),
    isPopular: true,
    sortOrder: 3,
  },
  {
    id: "sz_chicken_butter_masala",
    categoryId: "cat_sz_nonveg_main",
    name: "Chicken Butter Masala",
    description: "Tender chicken pieces in rich creamy butter makhani gravy.",
    isVeg: false,
    pricePaise: R(249),
    isPopular: true,
    sortOrder: 4,
  },
  {
    id: "sz_chicken_do_pyaza",
    categoryId: "cat_sz_nonveg_main",
    name: "Chicken Do-Pyaza",
    description: "Chicken curry cooked with sautéed pearl onions.",
    isVeg: false,
    pricePaise: R(239),
    sortOrder: 5,
  },
  {
    id: "sz_chicken_kadhai",
    categoryId: "cat_sz_nonveg_main",
    name: "Chicken Kadhai",
    description: "Wok-cooked chicken with bell peppers and roasted coriander.",
    isVeg: false,
    pricePaise: R(249),
    sortOrder: 6,
  },
  {
    id: "sz_chicken_tikka_butter_masala",
    categoryId: "cat_sz_nonveg_main",
    name: "Chicken Tikka Butter Masala",
    description: "Tandoori chicken tikkas in rich butter gravy.",
    isVeg: false,
    pricePaise: R(259),
    isPopular: true,
    sortOrder: 7,
  },
  {
    id: "sz_egg_curry_2pc",
    categoryId: "cat_sz_nonveg_main",
    name: "Egg Curry (2 Pc)",
    description: "Two boiled eggs in spiced curry.",
    isVeg: false,
    pricePaise: R(99),
    sortOrder: 8,
  },
  {
    id: "sz_egg_bhurji",
    categoryId: "cat_sz_nonveg_main",
    name: "Egg Bhurji",
    description: "Scrambled eggs with onions, green chillies and coriander.",
    isVeg: false,
    pricePaise: R(89),
    sortOrder: 9,
  },
  {
    id: "sz_fish_curry_2pc",
    categoryId: "cat_sz_nonveg_main",
    name: "Fish Curry (2 Pc)",
    description: "Fresh fish steaks in traditional mustard curry.",
    isVeg: false,
    pricePaise: R(129),
    sortOrder: 10,
  },
  {
    id: "sz_fish_fry_2pc",
    categoryId: "cat_sz_nonveg_main",
    name: "Fish Fry (2 Pc)",
    description: "Crispy pan-fried marinated fish pieces.",
    isVeg: false,
    pricePaise: R(119),
    sortOrder: 11,
  },

  // ── 17. BIRYANI ──────────────────────────────────────────────────────
  {
    id: "sz_veg_biryani",
    categoryId: "cat_sz_biryani",
    name: "Veg Biryani",
    description: "Fragrant basmati rice layered with vegetables and spices.",
    isVeg: true,
    pricePaise: R(119),
    sortOrder: 1,
  },
  {
    id: "sz_chicken_dum_biryani",
    categoryId: "cat_sz_biryani",
    name: "Chicken Dum Biryani",
    description: "Slow-cooked dum biryani with tender chicken pieces.",
    isVeg: false,
    pricePaise: R(149),
    isPopular: true,
    sortOrder: 2,
  },
  {
    id: "sz_hyderabadi_biryani",
    categoryId: "cat_sz_biryani",
    name: "Hyderabadi Biryani",
    description: "Spicy Hyderabadi dum rice with chicken and spices.",
    isVeg: false,
    pricePaise: R(149),
    isPopular: true,
    sortOrder: 3,
  },
  {
    id: "sz_egg_biryani",
    categoryId: "cat_sz_biryani",
    name: "Egg Biryani",
    description: "Aromatic basmati rice cooked with spiced boiled eggs.",
    isVeg: false,
    pricePaise: R(139),
    sortOrder: 4,
  },

  // ── 18. DAL & RICE ───────────────────────────────────────────────────
  {
    id: "sz_dal_fry",
    categoryId: "cat_sz_dal_rice",
    name: "Dal Fry",
    description: "Yellow toor dal tempered with cumin, garlic and ghee.",
    isVeg: true,
    pricePaise: R(99),
    sortOrder: 1,
  },
  {
    id: "sz_dal_tadka",
    categoryId: "cat_sz_dal_rice",
    name: "Dal Tadka",
    description: "Yellow lentils finished with double desi ghee tadka.",
    isVeg: true,
    pricePaise: R(99),
    isPopular: true,
    sortOrder: 2,
  },
  {
    id: "sz_plain_dal",
    categoryId: "cat_sz_dal_rice",
    name: "Plain Dal",
    description: "Simple homestyle boiled yellow dal.",
    isVeg: true,
    pricePaise: R(79),
    sortOrder: 3,
  },
  {
    id: "sz_plain_rice",
    categoryId: "cat_sz_dal_rice",
    name: "Plain Rice",
    description: "Steamed fluffy basmati rice.",
    isVeg: true,
    pricePaise: R(60),
    sortOrder: 4,
  },
  {
    id: "sz_jeera_rice",
    categoryId: "cat_sz_dal_rice",
    name: "Jeera Rice",
    description: "Basmati rice tempered with cumin seeds and ghee.",
    isVeg: true,
    pricePaise: R(80),
    sortOrder: 5,
  },
  {
    id: "sz_matar_pulao",
    categoryId: "cat_sz_dal_rice",
    name: "Matar Pulao",
    description: "Basmati rice cooked with fresh green peas and mild spices.",
    isVeg: true,
    pricePaise: R(120),
    sortOrder: 6,
  },
  {
    id: "sz_veg_pulao",
    categoryId: "cat_sz_dal_rice",
    name: "Veg Pulao",
    description: "Fragrant pulao with diced seasonal vegetables.",
    isVeg: true,
    pricePaise: R(130),
    sortOrder: 7,
  },

  // ── 19. SPECIAL THALIS ───────────────────────────────────────────────
  {
    id: "sz_normal_veg_thali",
    categoryId: "cat_sz_thali",
    name: "Normal Veg Thali",
    description: "2 Sabji + Dal + Chawal + 2 Roti + Salad.",
    isVeg: true,
    pricePaise: R(129),
    isPopular: true,
    sortOrder: 1,
  },
  {
    id: "sz_special_veg_thali",
    categoryId: "cat_sz_thali",
    name: "Special Veg Thali",
    description: "2 Sabji + Dal + Chawal + 2 Roti + Salad + Papad / Raita.",
    isVeg: true,
    pricePaise: R(149),
    isPopular: true,
    sortOrder: 2,
  },
  {
    id: "sz_premium_veg_thali",
    categoryId: "cat_sz_thali",
    name: "Premium Veg Thali",
    description: "Paneer Sabji + Seasonal Sabji + Dal + Chawal + 2 Roti + Salad + Raita + Sweet.",
    isVeg: true,
    pricePaise: R(199),
    isPopular: true,
    sortOrder: 3,
  },

  // ── 20. INDIAN BREADS ────────────────────────────────────────────────
  {
    id: "sz_tawa_roti",
    categoryId: "cat_sz_breads",
    name: "Tawa Roti",
    description: "Homestyle whole wheat flatbread on tawa.",
    isVeg: true,
    pricePaise: R(12),
    addOnGroups: [butterOptionGroup(R(12), R(16))],
    sortOrder: 1,
  },
  {
    id: "sz_tandoori_roti",
    categoryId: "cat_sz_breads",
    name: "Tandoori Roti",
    description: "Crispy wheat bread baked in clay tandoor.",
    isVeg: true,
    pricePaise: R(16),
    addOnGroups: [butterOptionGroup(R(16), R(20))],
    sortOrder: 2,
  },
  {
    id: "sz_plain_paratha",
    categoryId: "cat_sz_breads",
    name: "Plain Paratha",
    description: "Layered tawa flatbread.",
    isVeg: true,
    pricePaise: R(25),
    sortOrder: 3,
  },
  {
    id: "sz_aloo_paratha",
    categoryId: "cat_sz_breads",
    name: "Aloo Paratha",
    description: "Stuffed with spiced potato filling.",
    isVeg: true,
    pricePaise: R(50),
    isPopular: true,
    sortOrder: 4,
  },
  {
    id: "sz_paneer_paratha",
    categoryId: "cat_sz_breads",
    name: "Paneer Paratha",
    description: "Stuffed with seasoned grated paneer.",
    isVeg: true,
    pricePaise: R(60),
    isPopular: true,
    sortOrder: 5,
  },
  {
    id: "sz_butter_naan",
    categoryId: "cat_sz_breads",
    name: "Butter Naan",
    description: "Soft leavened tandoor naan brushed with butter.",
    isVeg: true,
    pricePaise: R(35),
    isPopular: true,
    sortOrder: 6,
  },
  {
    id: "sz_aloo_naan",
    categoryId: "cat_sz_breads",
    name: "Aloo Naan",
    description: "Tandoori naan stuffed with spicy potatoes.",
    isVeg: true,
    pricePaise: R(40),
    sortOrder: 7,
  },

  // ── 21. SOUPS ────────────────────────────────────────────────────────
  {
    id: "sz_manchow_soup",
    categoryId: "cat_sz_soups",
    name: "Manchow Soup",
    description: "Spicy garlic vegetable soup with fried noodles.",
    isVeg: true,
    pricePaise: R(59),
    sortOrder: 1,
  },
  {
    id: "sz_hot_sour_soup",
    categoryId: "cat_sz_soups",
    name: "Hot & Sour Soup",
    description: "Tangy and spicy pepper broth.",
    isVeg: true,
    pricePaise: R(59),
    sortOrder: 2,
  },
  {
    id: "sz_sweet_corn_soup",
    categoryId: "cat_sz_soups",
    name: "Sweet Corn Soup",
    description: "Comforting creamy golden corn soup.",
    isVeg: true,
    pricePaise: R(59),
    sortOrder: 3,
  },
  {
    id: "sz_cream_of_tomato",
    categoryId: "cat_sz_soups",
    name: "Cream of Tomato",
    description: "Velvety smooth tomato soup with butter.",
    isVeg: true,
    pricePaise: R(59),
    sortOrder: 4,
  },
  {
    id: "sz_special_veg_soup",
    categoryId: "cat_sz_soups",
    name: "Sone Zone Special Veg Soup",
    description: "Chef's special loaded vegetable herb soup.",
    isVeg: true,
    pricePaise: R(79),
    sortOrder: 5,
  },
  {
    id: "sz_chicken_sweet_corn_soup",
    categoryId: "cat_sz_soups",
    name: "Chicken Sweet Corn Soup",
    description: "Sweet corn soup with shredded chicken.",
    isVeg: false,
    pricePaise: R(89),
    sortOrder: 6,
  },
  {
    id: "sz_chicken_hot_sour_soup",
    categoryId: "cat_sz_soups",
    name: "Chicken Hot & Sour Soup",
    description: "Fiery spicy chicken broth soup.",
    isVeg: false,
    pricePaise: R(89),
    sortOrder: 7,
  },
  {
    id: "sz_special_nonveg_soup",
    categoryId: "cat_sz_soups",
    name: "Sone Zone Special Non-Veg Soup",
    description: "Chef's signature rich chicken and egg soup.",
    isVeg: false,
    pricePaise: R(99),
    isPopular: true,
    sortOrder: 8,
  },
];

/* ══════════════════════════════════════════════════════════════════════
   Main Seed Runner
   ══════════════════════════════════════════════════════════════════════ */

export async function seedSoneZone(): Promise<void> {
  console.log("=== Onboarding Sone Zone Cafe ===");

  const campusesCollection = await db.campuses();
  const campus = await campusesCollection.findOne({ _id: CAMPUS_ID });
  if (!campus) {
    throw new Error(`Campus "${CAMPUS_ID}" not found. Run "npm run seed" first.`);
  }

  const now = new Date();
  const servedZoneIds = campus.zones.map((z) => z.id);

  // 1. Upsert Restaurant
  const restaurant: Restaurant = {
    _id: RESTAURANT_ID,
    campusId: CAMPUS_ID,
    slug: "sone-zone-cafe",
    name: "Sone Zone Cafe",
    cuisines: [
      "Cafe",
      "Beverages",
      "Fast Food",
      "North Indian",
      "Chinese",
      "Pizza",
      "South Indian",
      "Biryani",
      "Thalis",
    ],
    phone: "9876543212",
    description:
      "Sone Zone Cafe - Hot Tea, Shakes, Mocktails, Pizzas, Burgers, South Indian Dosas, Thalis, Momos & Chinese Delicacies.",
    imageUrl: null,
    bannerUrl: null,
    packagingFeePaise: R(10),
    minOrderPaise: R(40),
    prepMinutes: 15,
    foodGstBps: 0,
    commissionBpsOverride: null,
    servedZoneIds,
    opensMinutes: 0, // 24x7 service
    closesMinutes: 1439,
    isOpen: true,
    isApproved: true,
    rating: 4.6,
    ratingCount: 38,
    kyc: {
      status: "APPROVED",
      ownerName: "Sone Zone Manager",
      ownerPhone: "9876543212",
      gstin: null,
      fssai: null,
      reviewedAt: now,
      reviewedBy: "user_admin",
      rejectionReason: null,
    },
    payout: {
      accountName: "Sone Zone Cafe",
      accountNumber: "987654321200",
      ifsc: "SBIN0001234",
      upiId: "sonezone@upi",
    },
    expiryCountToday: 0,
    autoClosedAt: null,
    createdAt: now,
    updatedAt: now,
  };

  const restaurantsCollection = await db.restaurants();
  await restaurantsCollection.replaceOne({ _id: RESTAURANT_ID }, restaurant, { upsert: true });
  console.log(`[x] Restaurant "${restaurant.name}" created/updated.`);

  // 2. Upsert Vendor Account
  const usersCollection = await db.users();
  const vendorUser: User = {
    _id: VENDOR_USER_ID,
    authId: null,
    role: ROLE.VENDOR_OWNER,
    name: "Sone Zone Manager",
    email: VENDOR_EMAIL,
    phone: "9876543212",
    passwordHash: hashPassword("sonezonecafe@1995"),
    campusId: CAMPUS_ID,
    restaurantId: RESTAURANT_ID,
    codBlocked: false,
    codBlockedReason: null,
    strikes: 0,
    createdAt: now,
    updatedAt: now,
  };

  await usersCollection.replaceOne({ _id: VENDOR_USER_ID }, vendorUser, { upsert: true });
  console.log(`[x] Vendor User "${VENDOR_EMAIL}" created/updated.`);

  // 3. Upsert Categories
  const categoriesCollection = await db.menuCategories();
  await categoriesCollection.deleteMany({ restaurantId: RESTAURANT_ID });

  const categoryDocs: MenuCategory[] = CATEGORIES.map((cat) => ({
    _id: cat.id,
    restaurantId: RESTAURANT_ID,
    name: cat.name,
    sortOrder: cat.sortOrder,
  }));

  await categoriesCollection.insertMany(categoryDocs);
  console.log(`[x] ${categoryDocs.length} menu categories seeded.`);

  // 4. Upsert Menu Items
  const itemsCollection = await db.menuItems();
  await itemsCollection.deleteMany({ restaurantId: RESTAURANT_ID });

  const itemDocs: MenuItem[] = ITEMS.map((item) => ({
    _id: item.id,
    restaurantId: RESTAURANT_ID,
    categoryId: item.categoryId,
    name: item.name,
    description: item.description,
    isVeg: item.isVeg,
    pricePaise: item.pricePaise,
    imageUrl: null,
    isAvailable: true,
    isPopular: item.isPopular ?? false,
    addOnGroups: item.addOnGroups ?? [],
    sortOrder: item.sortOrder,
  }));

  await itemsCollection.insertMany(itemDocs);
  console.log(`[x] ${itemDocs.length} menu items seeded with size & preparation options.`);

  console.log("\n=== Sone Zone Cafe Ready! ===");
  console.log(`  - Student URL: /c/${campus.slug}/r/${restaurant.slug}`);
  console.log(`  - Admin Menu URL: /admin/vendors/${RESTAURANT_ID}/menu`);
  console.log(`  - Vendor Login: ${VENDOR_EMAIL} / sonezonecafe@1995`);
}

async function main() {
  try {
    await seedSoneZone();
  } finally {
    const client = await getMongoClient();
    await client.close();
  }
}

if (require.main === module || process.argv[1]?.includes("seed-sone-zone")) {
  main().catch((err) => {
    console.error("Failed to seed Sone Zone Cafe:", err);
    process.exit(1);
  });
}
